### ISSUE TITLE
Coreprotect hook

### ISSUE THREAD

**Issue by amarcais53** [BG-Software-LLC/WildChests#100]
### Minecraft's Version

1.17.1

### Plugin's Version

latest dev build 

### Describe the bug

when i check with coreprotect who has break a sell chest it only say to me who placed it but dont say me who destroyed it
I'm not sure if there is a hook with coreprotect but i know wildstacker have one for spawners

### To Reproduce

place a sell chest break it and check it with /co inspect from coreprotect

**Comment by OmerBenGera** [comment]
WildChests doesnt support CoreProtect at this moment.
I will look into adding support tho

**Comment by amarcais53** [comment]
alright thank you that would be amazing

**Comment by OmerBenGera** [comment]
Added in latest dev build :)

**Comment by amarcais53** [comment]
ty :D
