### ISSUE TITLE
Selling Chest Bug

### ISSUE THREAD

**Issue by Zsomi** [BG-Software-LLC/WildChests#104]
### Minecraft's Version

Paper-1.16.5-794

### Plugin's Version

Dev version: 52

### Describe the bug

When I take the box to another location.

### To Reproduce

1. Place the chest.
2. Broke the chest
3. Place the chest again

### Additional Information

The crate revertes to a normal minecraft crate when I put it down again.

**Comment by OmerBenGera** [comment]
It works fine for me.
Maybe there's a conflict with another plugin - try the plugin on it's own on your server.

**Comment by OmerBenGera** [comment]
Any news regarding this?
