### ISSUE TITLE
WildStacker - override for stack

### ISSUE THREAD

**Issue by dan28000** [BG-Software-LLC/WildChests#106]
### Minecraft's Version

![image](https://user-images.githubusercontent.com/84990628/160185030-9ecfe3d5-d1c2-4f7d-9292-d4cd6e9919e0.png)

### Plugin's Version

Latest dev build
WildChests-2.3.0-b57.jar

### Describe the bug

When wildstacker is installed and it's set with all items for example to 1024 items, then if you brake storage_unit with for example 2048 items in chest and it will drop 2 stacks of 1024 items from wild stacker.

### To Reproduce

Have installed latest dev build of wildchests and version 3.7.0 of wildstacker 
1. set wildstacker in config to limit for all items to for example 1024
![image](https://user-images.githubusercontent.com/84990628/160186550-f7b0e46e-c857-439e-a815-efaf67657d5d.png)
2. restart server
3. place storage_unit fill it up with for example 2048 items
![image](https://user-images.githubusercontent.com/84990628/160186712-c684a5c6-8c8f-4c8c-b08b-d2914c645f59.png)
4. brake the storage_unit
5. there will be 2 stacks of 1024 items
![image](https://user-images.githubusercontent.com/84990628/160186827-6ba6bf0e-8eb1-46e5-9368-eae0f80b85a8.png)

### Additional Information

wildchests config stock config
wildstacker config everything stock execept the stack limit

**Comment by OmerBenGera** [comment]
What's the issue I do not understand?
It seems like the stacked items is respected just fine.

**Comment by dan28000** [comment]
Shouldn't it override max stack size of stack of wildstacker?
If this behavior is right then this can be turned into feature req that it will override max stack size of wildstacker config.
So if storage_unit has for example 10k items and wildstacker stacks everything to 1k then it will override it and create one stack of 10k.

**Comment by OmerBenGera** [comment]
It's a limit and nothing should override it.
If you don't want a limit, do not set one.
