### ISSUE TITLE
ShopGUI+ Update Breaks plugin

### ISSUE THREAD

**Issue by TigerRageMC** [BG-Software-LLC/WildChests#107]
### Minecraft's Version

Purpur 1.18.2 build 1599

### Plugin's Version

[v2.3.0] Latest

### Describe the bug

A new ShopGUI+ update came out which changed some of the API in the update. The auto sell chests don't work after I updated to it. 

[Error Message](https://pastebin.com/7sZZPV4f)

### To Reproduce

Sell an item with an auto sell chest to get a error in console.

**Comment by OmerBenGera** [comment]
Downgrade SGP for now :)

**Comment by OmerBenGera** [comment]
I forgot to update you that latest builds of the plugin fix the issue.
