### ISSUE TITLE
chunk collector doesn't activate until a block update happens

### ISSUE THREAD

**Issue by dburn4812** [BG-Software-LLC/WildChests#108]
### Minecraft's Version

1.8.8 Spigot

### Plugin's Version

Latest dev build

### Describe the bug

The chunk collector doesn't activate after being placed to fix this I normally have to put a hopper underneath it before it starts working 

### To Reproduce

spawn in chest and place it

**Comment by OmerBenGera** [comment]
I can't seem to replicate the issue.
What version of Spigot are you using exactly?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by dburn4812** [comment]
Spigot 1.8.8-R0.1 latest snapshot 
When I use sell chests they don't activate immediately and instead has to have a block update like a hopper placed under it is what i normally do and when it does work and the server resets it stops working
This is the config i have for it with auto suction on
 sell_chest:
    chest-mode: CHEST
    size: 6
    title: Drop your items here to sell them.
    item:
      name: '&dSell Chest &7(Place to active)'
    auto-suction:
      range: 256
      chunk: true
    sell-mode: true
    particles:
    - SPELL_WITCH

**Comment by OmerBenGera** [comment]
I will look into that again
Send me the output of /version

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by dburn4812** [comment]
![2022-06-11_21 53 49](https://user-images.githubusercontent.com/84989539/173210986-04a88b4f-0dbc-4e97-a9a7-f063ab92181c.png)

**Comment by dburn4812** [comment]
Also I was wondering if there is a way to make an item not even appear and just automatically go into the chest without appearing at all because that would help lag a lot for my server

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
