### ISSUE TITLE
duplicate items without restriction

### ISSUE THREAD

**Issue by fyxrim** [BG-Software-LLC/WildChests#109]
### Minecraft's Version

![image](https://user-images.githubusercontent.com/41105875/162845095-088d3d40-5bc4-4e06-a109-2fe0390cd6d0.png)

### Plugin's Version

我使用最新 2.3.0.58

### Describe the bug

https://www.spigotmc.org/resources/upgradeable-hoppers-fast-hopper-plugin-link-containers-item-transfer-suction-chunk-1-18-support.69201/
![image](https://user-images.githubusercontent.com/41105875/162845315-1bda1d68-830c-40d3-ad90-c7c7b8611c99.png)
![image](https://user-images.githubusercontent.com/41105875/162845334-b9a988e8-4370-4c4a-85ea-2557133778f8.png)

### To Reproduce

duplicate items without restriction

### Additional Information

https://user-images.githubusercontent.com/41105875/162845190-eaeba0aa-6c72-4fbd-80e1-bc013ae93321.mp4

**Comment by OmerBenGera** [comment]
I contacted Angeschossen, hopefully he will respond soon :)

**Comment by OmerBenGera** [comment]
I can't replicate the issue - I placed a hopper underneath and linked it into the storage unit, it seems to work fine.
Are you able to replicate the issue on localhost where you only have UpgradableHoppers and WildChests installed?

**Comment by fyxrim** [comment]
![AUF}2LKC}52L(B~RK%8GU%3](https://user-images.githubusercontent.com/41105875/163736880-a9d3858f-9105-4111-bbd4-5b122119ce1a.png)
https://cdn.discordapp.com/attachments/964458657649672234/965400964355985428/Jdk-17.0.1_2022.04.18_-_07.52.10.01_x264.mp4
I use to download the latest version, but there are still serious errors

**Comment by OmerBenGera** [comment]
Send me your configuration file of UH, it might be something related to that

**Comment by fyxrim** [comment]
[UpgradeableHoppers.zip](https://github.com/BG-Software-LLC/WildChests/files/8505078/UpgradeableHoppers.zip)

**Comment by fyxrim** [comment]
> Send me your configuration file of UH, it might be something related to that
[UpgradeableHoppers.zip](https://github.com/BG-Software-LLC/WildChests/files/8505081/UpgradeableHoppers.zip)

**Comment by fyxrim** [comment]
discord: AkkLive#9013

**Comment by OmerBenGera** [comment]
Send me your WC configuration file as well.

**Comment by fyxrim** [comment]
#########################################################
##                                                     ##
##              WildChests Configuration               ##
##                 Developed by Ome_R                  ##
##                                                     ##
#########################################################

# How much time should be passed between sell and crafting notifies? (in ticks)
# Set 0 to disable this feature.
notifier-interval: 12000

# When enabled there will be a list of items that has been sold and crafted.
detailed-notifier: true

# When enabled, a gui will be popped to confirm chest expand purchase. Otherwise, it will be done in chat.
confirm-gui: false

# Specify a command to be executed when a sell is running.
# {player-name} - use as the player's name
# {price} - use as the price of item
# Set to '' in order to disable the feature.
sell-command: ''

# When enabled, the values will be formatted (e.g 10B, 1T)
sell-format: false

# Should the chest item be dropped on explosions?
# Set a chance of it to get dropped between 0 and 100.
explode-drop-chance: 100

# What prices provider should the plugin use? (CMI, ShopGUIPlus, QuantumShop, Essentials, zShop, WildChests)
prices-provider: ShopGUIPlus

# Built-in prices list.
# Use the "ID:PRICE" or "ID:DATA:PRICE" formats.
prices-list:
- STONE:5
- LOG:0:5

# All settings related to database.
database:
  # Automatically delete data from invalid worlds.
  invalid-world-delete: true

# All settings related to hooks
hooks:
  # Should items dropped by the plugin get directly stacked by WildStacker?
  wildstacker: true

# The maximum pickup delay items can have for the suction chests to pick them up.
maximum-pickup-delay: 32767

# The plugin brings tons of new custom and unique chests to your server. All the chests are configurable, and
# you can create and mix between them. You can create chests that stores infinite amount of items, chests that
# are connected to player vaults or factions, linked chests and many more!
#
# *** Chest Mode ***
# Chests in this mode react like regular chests. This is the base mode, and used for creating
# sell chests and larger chests.
#
# *** Linked Mode ***
# Chests in this mode are all linked together, and work like ender chests, but globally.
#
# *** Storage Units Mode ***
# Chests in this mode will have unlimited amount of storage, but only for one specific item.
# Note: Auto sell & auto craft modes doesn't work for this mode!
#
# There are sections that can be applied to all of the chests:
# size: Amount of rows the chest will have (INTEGER) (Will be overridden by pages' size)
# title: Global title for all pages. Will be overridden by page's title (STRING)
# sell-chest: Should items in this chest will be sold to the chest placer? (BOOLEAN)
# crafter-chest: List of recipes that will take action in this chest (LIST)
#      Please follow "TYPE" and "TYPE:DATA" formats
# hopper-filter: When enabled, only craftable items will go into hoppers below (BOOLEAN)
# pages: Section that handles all settings for pages
# pages.default: Default amount of pages (INTEGER) [REQUIRED FOR PAGES]
# pages.<#>: Section that handles all settings for a specific page
# pages.<#>.price: Price for upgrading to that page (DOUBLE) [REQUIRED]
# pages.<#>.title: Custom title for that page.
# item.name: Custom name for the chest (STRING)
# item.lore: Custom lore for the chest (LIST)
# multiplier: Money multiplier for sell chests. (DOUBLE)
# deposit-method: Transfer the money received by the sell chest to a skyblock/faction bank
#     Currently supported: Vault, SuperiorSkyblock2
# auto-collect: Should items get directly into inventory after breaking? (BOOLEAN)
# auto-suction.range: Should items inside the specified range will get suctioned into the chest? (INTEGER)
# auto-suction.chunk: Should items inside the chunk will get suctioned into the chest? (BOOLEAN)
#      If you set it to true, the range will be checked as y-range only.
# blacklist: A list of items that won't be picked up by the chests (only works for auto-suction for now)
# whitelist: A list of items that will be picked up by the chests (only works for auto-suction for now)
# particles: A list of particles that will be shown to the chest.

chests:
  远程连接:
    chest-mode: LINKED_CHEST
    title: '&l用/chests link选择另一个箱子来连接'
    item:
      name: §x§0§C§9§A§E§B§l远程连接箱
    particles:
    - CRIT
  大箱子:
    chest-mode: CHEST
    size: 6
    item:
      name: §x§0§C§9§A§E§B§l更多箱子箱
    pages:
      '1':
        price: 0
        title: '&l大箱子 (1页)'
      '2':
        price: 0
        title: '&l大箱子 (2页)'
      '3':
        price: 0
        title: '&l大箱子 (3页)'
      '4':
        price: 0
        title: '&l大箱子 (4页)'
      '5':
        price: 0
        title: '&l大箱子 (5页)'
      '6':
        price: 0
        title: '&l大箱子 (6页)'
      '7':
        price: 0
        title: '&l大箱子 (7页)'
      '8':
        price: 0
        title: '&l大箱子 (8页)'
      '9':
        price: 0
        title: '&l大箱子 (9页)'
      '10':
        price: 0
        title: '&l大箱子 (10页)'
    particles:
    - TOTEM
  sell_chest:
    chest-mode: CHEST
    size: 6
    title: Drop your items here to sell them.
    item:
      name: '&dSell Chest &7(Place to active)'
    sell-mode: true
    particles:
    - SPELL_WITCH
  自动压缩:
    chest-mode: CHEST
    size: 6
    title: §l将您的物品放在自动合成它们
    item:
      name: §x§0§C§9§A§E§B§l自动压缩箱
    crafter-chest:
    - GOLD_BLOCK
    - IRON_BLOCK
    - COPPER_BLOCK
    - REDSTONE_BLOCK
    - DIAMOND_BLOCK
    - EMERALD_BLOCK
    - LAPIS_BLOCK
    - QUARTZ_BLOCK
    - COAL_BLOCK
    particles:
    - LANDING_LAVA
  存储单元:
    chest-mode: STORAGE_UNIT
    size: 3
    title: §b§l存储单元 {0}
    item:
      name: §x§0§C§9§A§E§B§l储存单元箱
    particles:
    - CRIT_MAGIC
  区块收集器:
    chest-mode: CHEST
    size: 6
    title: Chunk Collector
    item:
      name: §x§0§C§9§A§E§B§l区块收集箱
    auto-suction:
      range: 10
      chunk: true
    particles:
    - SMOKE_NORMAL
    - FLAME

**Comment by fyxrim** [comment]
> Send me your WC configuration file as well. Upload it to pastebin and send it here

https://pastebin.com/GELskpfT

**Comment by fyxrim** [comment]
It's been two months, has it been fixed?

**Comment by OmerBenGera** [comment]
> It's been two months, has it been fixed?

Not yet, sadly.
Havent figured it out yet.
Only 1 week ago I managed to replicate the issue myself.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
