### ISSUE TITLE
QuantumShop (ExcellentShop) is not working as a price provider.

### ISSUE THREAD

**Issue by Proggyr** [BG-Software-LLC/WildChests#111]
### Minecraft's Version

Minecraft Version 1.18.2
Paper 1.18.2-283 (Server version)

### Plugin's Version

WildChests-2.3.0

### Describe the bug

Not registering QuantumShop in the price provider.

### To Reproduce

Just put QuantumShop as a price provider and it doesn't work.

### Additional Information

![image](https://user-images.githubusercontent.com/94422192/167250865-35b6a7af-51a6-422a-9427-44d743bcf9df.png)

![image](https://user-images.githubusercontent.com/94422192/167250873-f50db272-f689-4bb5-a679-46eeab08e383.png)

**Comment by OmerBenGera** [comment]
That's because it's technically another plugin now :)
I opened a ticket for you on discord so you can send me a copy of the plugin so I can add support for it
