### ISSUE TITLE
Chests selling/collecting NBT items

### ISSUE THREAD

**Issue by DuneSciFye** [BG-Software-LLC/WildChests#114]
### Minecraft's Version

git-Purpur-1609 (MC: 1.18.2)*

### Plugin's Version

WildChests version 2.3.0

### Describe the bug

Custom Chests from WildChests sell, auto pickup, and use to craft items with NBT tags. I asked this on the GitHub and was told "Make an issue on github, somewhat a known issue."

### To Reproduce

1. Get an auto collector chest
2. Get an item with NBT tags
3. Drop the item

**Comment by OmerBenGera** [comment]
You want chests to not pickup items with custom nbt tags..?

**Comment by DuneSciFye** [comment]
Yes, or sell, because other plugins may have custom items, which the chests may accidentally pick up and sell.

**Comment by OmerBenGera** [comment]
> Yes, or sell, because other plugins may have custom items, which the chests may accidentally pick up and sell.

Such as...?
Plugins can disable pickup of items by making the pickup delay high.

**Comment by DuneSciFye** [comment]
My main concern is ExecutableItems, where I have a lot of custom items made from that, such as material used to craft other custom items. Another one is weapons and armor with custom enchants that are stored with NBT tags.

**Comment by OmerBenGera** [comment]
> My main concern is ExecutableItems, where I have a lot of custom items made from that, such as material used to craft other custom items. Another one is weapons and armor with custom enchants that are stored with NBT tags.

If they are "regular items", then there's no reason for Wildchests to not pick them up.
"Custom nbts" is not something that easy to implement - all the data of items are stored as nbts, therefore checking for custom items is not really easy.
As of now, the plugin will pick up all items and that's an intended behavior, including ones with custom nbts.
