### ISSUE TITLE
Very big duplication bug & infinite money generating

### ISSUE THREAD

**Issue by xXiArley** [BG-Software-LLC/WildChests#116]
### Minecraft's Version

1.17.1 

### Plugin's Version

2.3.0

### Describe the bug

If you have 2 linked chests and you put a  minion from plugin  jetminsion it will make money but the items dont disappear. And continue to sell the same item. (it is not a problem of jetsminions, I already talked with them) 

### To Reproduce

For reproduce the bug you have to take 2 Linked Chests and link them each other, if you link the first chest to a minion seller the system works correctly, but if you link the second or third etc chest to the minion it sells the item but they not dissapear. 

### Additional Information

Here a video that explain in a few second https://vimeo.com/715316028

**Comment by OmerBenGera** [comment]
I contacted Jet to get access to the plugin so I can look into it.
It may take some time until it's patched.

**Comment by xXiArley** [comment]
Ok thank you very much.. hope to find a patch.. Have good work and a good day.

**Comment by xXiArley** [comment]
Hello.. I'm so sorry.. do you have any news about that?

**Comment by OmerBenGera** [comment]
Not yet, hopefully will look into it this weekend :)

**Comment by OmerBenGera** [comment]
Should be fixed in latest dev build.
Let me know if it works for you

**Comment by OmerBenGera** [comment]
Closing this for now
If it still happens, let me know
