### ISSUE TITLE
1.19 Experimental Builds 

### ISSUE THREAD

**Issue by OmerBenGera** [BG-Software-LLC/WildChests#117]
This issue is a global issue to report bugs related to the 1.19 experimental builds.

You can find the experimental builds on https://hub.bg-software.com/job/1.19%20Experimental%20Builds/

**Comment by broken1arrow** [comment]
Crafting chest not work and link command not work ether. I don´t installed vault or economy (but should not needed for this two things). Will check sell chest and page chest (if get more pages work but need ofc vault). I will also check chunk load/unload also.
![2022-06-10_19 39 00](https://user-images.githubusercontent.com/16368286/173121616-217b9022-2ac9-469b-bc93-5da82f4f0a7a.png)

**Comment by OmerBenGera** [comment]
> Crafting chest not work and link command not work ether. I don´t installed vault or economy (but should not needed for this two things). Will check sell chest and page chest (if get more pages work but need ofc vault). I will also check chunk load/unload also.
> 
> paper 1.19-r0.1-snapshot version 5 ![2022-06-10_19 39 00](https://user-images.githubusercontent.com/16368286/173121616-217b9022-2ac9-469b-bc93-5da82f4f0a7a.png)

Fixed :)
Update to build 2

**Comment by broken1arrow** [comment]
> > Crafting chest not work and link command not work ether. I don´t installed vault or economy (but should not needed for this two things). Will check sell chest and page chest (if get more pages work but need ofc vault). I will also check chunk load/unload also.
> > paper 1.19-r0.1-snapshot version 5 ![2022-06-10_19 39 00](https://user-images.githubusercontent.com/16368286/173121616-217b9022-2ac9-469b-bc93-5da82f4f0a7a.png)
> 
> Fixed :) Update to build 2

Most is fixed (it craft items,sell and chunk collector pick up items), but can´t still link a chest.  should be /wildchests:chests link or /chests link and look on the chest to start the linking?

It say it not find valid linked chest.

**Comment by OmerBenGera** [comment]
> > > Crafting chest not work and link command not work ether. I don´t installed vault or economy (but should not needed for this two things). Will check sell chest and page chest (if get more pages work but need ofc vault). I will also check chunk load/unload also.
> > > paper 1.19-r0.1-snapshot version 5 ![2022-06-10_19 39 00](https://user-images.githubusercontent.com/16368286/173121616-217b9022-2ac9-469b-bc93-5da82f4f0a7a.png)
> > 
> > 
> > Fixed :) Update to build 2
> 
> Most is fixed (it craft items,sell and chunk collector pick up items), but can´t still link a chest. should be /wildchests:chests link or /chests link and look on the chest to start the linking?
> 
> It say it not find valid linked chest. Will try next paper build also.
> 
> new paper build seams not break this plugin. but linking seams not working still.

You must have the chest configured as linked chest and not regular one.
Anyways I checked it and it works fine

**Comment by broken1arrow** [comment]
> > > > Crafting chest not work and link command not work ether. I don´t installed vault or economy (but should not needed for this two things). Will check sell chest and page chest (if get more pages work but need ofc vault). I will also check chunk load/unload also.
> > > > paper 1.19-r0.1-snapshot version 5 ![2022-06-10_19 39 00](https://user-images.githubusercontent.com/16368286/173121616-217b9022-2ac9-469b-bc93-5da82f4f0a7a.png)
> > > 
> > > 
> > > Fixed :) Update to build 2
> > 
> > 
> > Most is fixed (it craft items,sell and chunk collector pick up items), but can´t still link a chest. should be /wildchests:chests link or /chests link and look on the chest to start the linking?
> > It say it not find valid linked chest. Will try next paper build also.
> > new paper build seams not break this plugin. but linking seams not working still.
> 
> You must have the chest configured as linked chest and not regular one. Anyways I checked it and it works fine
alright do i mess some setting I not see in the config ? https://pastebin.com/mxrHCUK6

**Comment by broken1arrow** [comment]
> > > > Crafting chest not work and link command not work ether. I don´t installed vault or economy (but should not needed for this two things). Will check sell chest and page chest (if get more pages work but need ofc vault). I will also check chunk load/unload also.
> > > > paper 1.19-r0.1-snapshot version 5 ![2022-06-10_19 39 00](https://user-images.githubusercontent.com/16368286/173121616-217b9022-2ac9-469b-bc93-5da82f4f0a7a.png)
> > > 
> > > 
> > > Fixed :) Update to build 2
> > 
> > 
> > Most is fixed (it craft items,sell and chunk collector pick up items), but can´t still link a chest. should be /wildchests:chests link or /chests link and look on the chest to start the linking?
> > It say it not find valid linked chest. Will try next paper build also.
> > new paper build seams not break this plugin. but linking seams not working still.
> 
> You must have the chest configured as linked chest and not regular one. Anyways I checked it and it works fine

alright seams like it not like it was snow layers between me and the chest. something you could look at?

**Comment by OmerBenGera** [comment]
> > > > > Crafting chest not work and link command not work ether. I don´t installed vault or economy (but should not needed for this two things). Will check sell chest and page chest (if get more pages work but need ofc vault). I will also check chunk load/unload also.
> > > > > paper 1.19-r0.1-snapshot version 5 ![2022-06-10_19 39 00](https://user-images.githubusercontent.com/16368286/173121616-217b9022-2ac9-469b-bc93-5da82f4f0a7a.png)
> > > > 
> > > > 
> > > > Fixed :) Update to build 2
> > > 
> > > 
> > > Most is fixed (it craft items,sell and chunk collector pick up items), but can´t still link a chest. should be /wildchests:chests link or /chests link and look on the chest to start the linking?
> > > It say it not find valid linked chest. Will try next paper build also.
> > > new paper build seams not break this plugin. but linking seams not working still.
> > 
> > 
> > You must have the chest configured as linked chest and not regular one. Anyways I checked it and it works fine
> 
> alright seams like it not like it was snow layers between me and the chest. something you could look at?

I don't think so, no.
Not related to 1.19 anyways :)

**Comment by broken1arrow** [comment]
so wont fix it then. I mean others will get some confusion of this :)
