### ISSUE TITLE
Legacy materials in PricesProvider

### ISSUE THREAD

**Issue by emmanuelvlad** [BG-Software-LLC/WildChests#119]
### Minecraft's Version

Purpur-1.18.2

### Plugin's Version

2.4.0

### Describe the bug

`PricesProvider.getPrice` gives an ItemStack with Legacy Material, so `SWEET_BERRIES` and `BAMBOO` are transformed to `AIR` and cannot be sold

### To Reproduce

```java
public class WildChestsHook implements PricesProvider {

    @Override
    public double getPrice(OfflinePlayer op, ItemStack item) {
        plugin.getLogger().info("Getting item:" + item.getData().getItemType());
        return 0.0;
    }
}
```

**Comment by OmerBenGera** [comment]
What about item#getType?
