### ISSUE TITLE
Sell Chest not selling Gold Ingots

### ISSUE THREAD

**Issue by max0r4axor** [BG-Software-LLC/WildChests#122]
### Minecraft's Version

1.18.2 Paper

### Plugin's Version

2.4.0 latest stable release

### Describe the bug

Sell chest sell everything Except Gold Ingots. I can sell Gold Ingots to ShopGui+ using 1.77.2 manually just not via the sell chest 

### To Reproduce

Gold ore is smelted to Gold Ingots and hoppers link Blast Furnace to Sell Chest and only the Gold Ingots wont sell.

**Comment by OmerBenGera** [comment]
Please upload your chest and how you configured it to pastebin and send it here

**Comment by max0r4axor** [comment]
It's the default configuration.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works now

**Comment by OmerBenGera** [comment]
Closing this for now
If the issue still occurs, let me know
