### ISSUE TITLE
Crash with 1.19.1

### ISSUE THREAD

**Issue by Celophy** [BG-Software-LLC/WildChests#126]
### Minecraft's Version

1.19.1

### Plugin's Version

last dev build

### Describe the bug

Crash when open a special chest

### To Reproduce

open a special chest

### Additional Information

Crash logo
[12:40:20] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.AbstractMethodError: Receiver class com.bgsoftware.wildchests.nms.NMSInventory_v1_19_R1$WildInventory does not define or inherit an implementation of the resolved method 'abstract int O_()' of interface net.minecraft.world.IInventory.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
