### ISSUE TITLE
Sell Chests dont sell anything

### ISSUE THREAD

**Issue by ThatNoobYeetR** [BG-Software-LLC/WildChests#127]
### Minecraft's Version

1.18.2 paper

### Plugin's Version

dev build 71

### Describe the bug

The sell chests do not sell anything at all

### To Reproduce

put something in a sell chest

**Comment by OmerBenGera** [comment]
What version of EconomyShopGUI do you use?

**Comment by ThatNoobYeetR** [comment]
> What version of EconomyShopGUI do you use?

4.7.1

**Comment by ThatNoobYeetR** [comment]
bump

**Comment by OmerBenGera** [comment]
> bump

There is no need to bump issues.
I will look into it whenever I have the time to.
Patient.

**Comment by OmerBenGera** [comment]
It works fine for me.
Did you set "EconomyShopGUI" as your prices-provider in the config file?

**Comment by ThatNoobYeetR** [comment]
> It works fine for me. Did you set "EconomyShopGUI" as your prices-provider in the config file?

worked
