### ISSUE TITLE
Breaking Storage Unit chests while there are more than 64 items only returns 64 items

### ISSUE THREAD

**Issue by ArmonicPvP** [BG-Software-LLC/WildChests#130]
### Minecraft's Version

1.19.1

### Plugin's Version

2.4.1 dev build 74

### Describe the bug

When you fill up a storage chest and break it while there are items in it, it will only drop max 64 items

### To Reproduce

Fill a storage unit chest past 64 items, then break

**Comment by OmerBenGera** [comment]
It works fine for me.
Test it on a server with only WildChests installed.

**Comment by ArmonicPvP** [comment]
The issue seems to happen when using WildStacker and WildChests with item stacking disabled in WildStacker config.

**Comment by OmerBenGera** [comment]
@ArmonicPvP Update WildStacker to latest dev build, let me know if it works now

**Comment by ArmonicPvP** [comment]
This is working now for me!
