### ISSUE TITLE
Chests selling less

### ISSUE THREAD

**Issue by DuneSciFye** [BG-Software-LLC/WildChests#132]
### Minecraft's Version

git-Purpur-1765 (MC:1.19.2)

### Plugin's Version

WildChests version 2.4.1.71

### Describe the bug

Sell chests sell a lot less items than they actually get. When using the sell chest in 10 minutes I get 30k, but when manually selling in 1 minute I get 12k.

### To Reproduce

Get a sell chest
Sell a ton of items from a farm at once

### Additional Information

![97D88A1A-5FF4-42FE-B8B0-ED5610CBCFB5](https://user-images.githubusercontent.com/65089425/187663327-ffb25002-b213-4458-adf5-2a4f30dfd61c.png)
![25E8AB3D-38CC-45A1-B115-6C50711359D0](https://user-images.githubusercontent.com/65089425/187663336-582d6a20-96ae-4a5b-8610-24e3ec2988c2.png)
![E5BDFB03-61D4-4B90-B604-44C119E472C0](https://user-images.githubusercontent.com/65089425/187663339-ac103cf7-0f09-445e-9b13-3139e5fabd96.png)
![5FE05E33-E390-4921-BBFE-7966A4F06FB7](https://user-images.githubusercontent.com/65089425/187663340-39b39dfe-2d33-47c5-a658-87e33010ad1d.png)
![1838BCD9-5FE5-489E-9463-840FD31F6366](https://user-images.githubusercontent.com/65089425/187663341-7bfd5c86-743f-4bcc-9342-ab500a1ef36b.png)

**Comment by OmerBenGera** [comment]
When an item is added to the chest it gets sold instantly.
There might be an issue that some items are just disappear (maybe due to the plugin?) and therefore they are not sold.
Are you able to replicate the issue yourself on another server with only WC and your shops plugin installed?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by DuneSciFye** [comment]
Sorry, apparently it resolved itself.
