### ISSUE TITLE
Wildchests and networks ( slimefu ) bug glitch

### ISSUE THREAD

**Issue by SrMonsterYT** [BG-Software-LLC/WildChests#133]
### Minecraft's Version

Pufferfish git-Pufferfish-36 (MC: 1.19.2)

### Plugin's Version

WildChests-2022.7-b80

### Describe the bug

using Networks VANILLA GRABBER and Networks VANILLA PUSHER from the slimefun addon (Networks), you can duplicate items infinitely, the video shows everything.

### To Reproduce

how to do the bug is in the link: https://youtu.be/KJ653aNp_oY

**Comment by OmerBenGera** [comment]
How are you able to put items that are not TNT in the storage unit?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue still occurs let me know by replying here
