### ISSUE TITLE
auto crafter crafting loop

### ISSUE THREAD

**Issue by amarcais53** [BG-Software-LLC/WildChests#137]
### Minecraft's Version

pufferfish 1.17.1

### Plugin's Version

latest dev

### Describe the bug

when adding the ability to craft GOLDEN_NUGGETS, GOLD_BLOCK, and GOLD_INGOT into an auto crafter chest it cause an infinite loop so it craft a gold ingot and then a block and then block is being uncrafted to gold ingot and gold ingot to gold nugget and doing that again and again so fast

### To Reproduce

do the setup i did before

**Comment by OmerBenGera** [comment]
Right, dont do that.
Not a bug
