### ISSUE TITLE
Chest Duplication Bug

### ISSUE THREAD

**Issue by DuneSciFye** [BG-Software-LLC/WildChests#138]
### Minecraft's Version

Current: git-Purpur-1765 (MC: 1.19.2)*

### Plugin's Version

WildChests version 2022.7

### Describe the bug

When linking multiple linked chests and breaking a specific one, it places a regular chest down.

### To Reproduce

1. Place down 4 Linked Chests
2. Link bottom left to bottom right
3. Link top left to top right
4. Link top left to bottom left, this should give you an internal error
5. Break bottom left chest, you should get linked chest back but a new regular chest appears

### Additional Information

https://streamable.com/u2q1eh

**Comment by OmerBenGera** [comment]
You had an error that you completely missed.
Send me the error that you received via pastebin.

**Comment by DuneSciFye** [comment]
Sorry about that, here you go: https://pastebin.com/xHJNL0ar

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by OmerBenGera** [comment]
I am closing this as it should be fixed.
If the issue still occurs let me know

**Comment by DuneSciFye** [comment]
Yup sorry for late reply, it was indeed fixed.
