### ISSUE TITLE
Wildchests deleting stacked items that go beyond vanilla limits with rosestacker

### ISSUE THREAD

**Issue by Acaendra** [BG-Software-LLC/WildChests#141]
### Minecraft's Version

1.19

### Plugin's Version

Wildchests 2.4.0

### Describe the bug

We use rosestacker for items. It allows us to go beyond the regular vanilla stacking limit but wildchests doesn't seem to like it and will delete the excess that it goes beyond when getting sucked into the wildchests themselves.

### To Reproduce

Placing items that goes beyond the vanilla stack limit with rosestacker will cause the wildchests to delete the excess items. 

Any chance there's a fix for that, or would it be something I should contact RoseStacker about?

**Comment by OmerBenGera** [comment]
RoseStacker needs to add support for RoseStacker:
https://github.com/BG-Software-LLC/WildChests/blob/35d092be517a9157915d41b1c5857b5c64f35216/API/src/main/java/com/bgsoftware/wildchests/api/handlers/ProvidersManager.java#L19

I'd do it myself however I don't have much time and I think them maintaining it will be better for the long run.

**Comment by emmanuelvlad** [comment]
It seems that the bug is still present even after https://github.com/BG-Software-LLC/WildChests/commit/173a56799cae255c73c0502be88a2a1316457955

**Comment by OmerBenGera** [comment]
> It seems that the bug is still present even after [173a567](https://github.com/BG-Software-LLC/WildChests/commit/173a56799cae255c73c0502be88a2a1316457955)

Open a new issue regarding this, not sure why you bump an issue that is 6 months old.
