### ISSUE TITLE
Sell chest does not work with economyshopgui

### ISSUE THREAD

**Issue by iJuju68** [BG-Software-LLC/WildChests#142]
### Minecraft's Version

1.8
PaperSpigot-« 4c7641d » MC 1.8.8

### Plugin's Version

Wildchests Version 2022.7
EconomyshopGUI version 5.0.0

### Describe the bug

When I put items in the sell chest they do not sell and remain in the chest while in the configuration I have specified that I use the plugin economyshopgui 

### To Reproduce

put the plugins Wildchests ans economyshopgui in the same version and the server in 1.8

**Comment by OmerBenGera** [comment]
It works fine for me.
Using latest version of WildChests, EconomyShopGUI and version `git-PaperSpigot-445`

**Comment by iJuju68** [comment]
However, the objects remain in the chest. Is there a configuration to do on economyshopgui?

**Comment by OmerBenGera** [comment]
> However, the objects remain in the chest. Is there a configuration to do on economyshopgui?

The items are withdrawn and removed from the chest when you close the chest.

**Comment by iJuju68** [comment]
Watch this video

https://user-images.githubusercontent.com/117361864/199972874-91015d22-b6d7-4a67-b341-d79950af797b.mp4

**Comment by OmerBenGera** [comment]
When the plugin loads, do you see "Using EconomyShopGUI as the prices provider" or something like that?

**Comment by iJuju68** [comment]
Yes i have this [WildChests]  - Using EconomyShopGUI as PricesProvider.

**Comment by OmerBenGera** [comment]
Does it still occur if you use it on a server with only WildChests and EconomyShopGUI installed?
Also, try using newer versions of Spigot (1.19.2, for example) - let me know if any of these steps help.

**Comment by iJuju68** [comment]
When I test without other plugins it works fine

**Comment by OmerBenGera** [comment]
> When I test without other plugins it works fine

Seems like another plugin might conflict with this.
Try adding the plugins one by one until you find the plugin that conflicts.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by iJuju68** [comment]
Sorry for the late reply, yes I have solved the problem thanks for your help!

**Comment by OmerBenGera** [comment]
> Sorry for the late reply, yes I have solved the problem thanks for your help!

I am glad to hear this.
What had caused the issue and how did you solve it?

**Comment by zaphod77** [comment]
This happened for me.
i'd set economyshopgui and it would pick zshop instead (!)

**Comment by OmerBenGera** [comment]
> This happened for me. i'd set economyshopgui and it would pick zshop instead (!) as in copy and paste from the config file itself to do this. (i watch the load log)

Fixed in latest dev build, sorry about that.
