### ISSUE TITLE
Potentially high server thread usage

### ISSUE THREAD

**Issue by mike-544** [BG-Software-LLC/WildChests#143]
### Minecraft's Version

Minecraft Version 1.19.2
(Cannot insert server.jar as its 37MB even when zipped and max allowed to upload is 25MB)

### Plugin's Version

[WildChests-2022.7-b80.zip](https://github.com/BG-Software-LLC/WildChests/files/10095824/WildChests-2022.7-b80.zip)

Wildchests version 2022,7-b80

### Describe the bug

TPS issues, used spark to get a profile: https://spark.lucko.me/u5FpZ05Ned

I had an issue with this a few weeks ago where it was using up around 61% of the server threat, but in this profile its only using up about 46% which is still a lot for a single plugin.

Advised by Ome_R in discord to make this issue on here

### To Reproduce

Players on this server can only have access to the sell chests, auto-collect chests, large chests and storage units. It appears to only really be a visible issue when i have about 15+ players online

Each player is allowed only 15 large chests with the config added in Additional Information, and each player that has a storage unit normally has it connected so a chunk hopper (from another plugin) collects the items, it feeds into a storage unit which then feeds down into large chests.
I thought maybe its the constant passing of items into and out of the storage units that might be causing the issue, but im obviously not the right one to make assumptions as i do not know whats actually going on in the plugin itself.

I also have the WildStacker plugin installed 

### Additional Information

**I use it on a farming server with this config:**
https://pastebin.com/yueA40GY

**Spigot Version: ** (I have no way of editing or changing this, this is controlled by Minehut the server host)

> This server is running Paper version git-Paper-215 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 236a296)
> You are 79 version(s) behind
> Download the new version at: https://papermc.io/downloads
> Previous version: git-Paper-131 (MC: 1.19.2)

**Comment by OmerBenGera** [comment]
What vsrsion of Spigot you use (exact output of /version)?
Also, get rid of the config from the issue's body and instead upload it to pastebin and include a link to it here.

**Comment by mike-544** [comment]
> 

Done

**Comment by broken1arrow** [comment]
I can say Minehut or other host are not good option specially when you have 15+ players (when we use host (paid one) it had problems to work with even 3 players with our setup of plugins (could not handle both jobs and mcmmo on same server)).

**Comment by mike-544** [comment]
The only thing is that when we did not have this plugin installed, we were handling 25-30 players at around 16-18tps. But in this time we have also installed some other plugins, but none that use anywhere near as much as the wildchest plugin seems to. So it might not be entirely the fault of this plugin but it could definitely be the main culprit

**Comment by broken1arrow** [comment]
> The only thing is that when we did not have this plugin installed, we were handling 25-30 players at around 16-18tps. But in this time we have also installed some other plugins, but none that use anywhere near as much as the wildchest plugin seems to. So it might not be entirely the fault of this plugin but it could definitely be the main culprit ![image](https://user-images.githubusercontent.com/110873635/204081150-f6ae9f1f-7e0e-47a9-b157-0ff3efc8041f.png)

I not say is not the plugin problem, only say on a host you has limit amount of performance.

But we notes the problem on several plugins had high timings (but not in this scale). But was lagging on the server when you try for example dig.

**Comment by mike-544** [comment]
https://spark.lucko.me/K0KmkO6sSl, another spark profile done today while tps around 16 with 8 players. 55%

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it's better.
Also make sure you take a spark profiler and send it here after you use it :)

**Comment by mike-544** [comment]
I will have to wait a few hours for the server to die down as most people afk overnight and i dont want them all to have a go that they got disconnected haha
But will let you know as soon as i can, thanks for responding and acting so quick, its much appreciated :)

**Comment by broken1arrow** [comment]
> Check out latest dev build, let me know if it's better. Also make sure you take a spark profiler and send it here after you use it :)

If I interpreters the report right from spark is it your toArray method some are the main issue (from getWildContents()). Your NonNullList cache are not the biggest issue here.

**Comment by broken1arrow** [comment]
When I self work with this, i always try keep list in "right" format, so less time consuming task I work with list and then convert it to array and then use the array directly (so i keep the array format in the field only add options how you want access it and save some ms that way).

**Comment by mike-544** [comment]
Ok so i have just tested it, and it broke my chunkhopper's that are placed on top of the wildchest chests, and i can no longer use the sell wand i made in skript on any of the wildchest chests. So there are some bigger issues that arose with that dev build

**Comment by broken1arrow** [comment]
> Ok so i have just tested it, and it broke my chunkhopper's that are placed on top of the wildchest chests, and i can no longer use the sell wand i made in skript on any of the wildchest chests. So there are some bigger issues that arose with that dev build
> 
> I am using the ChunkHopper plugin made by McDoJr

do normal hoppers works both below and ontop?

**Comment by mike-544** [comment]
No they throw a huge error in console when they try put something into a wildChests chest. Normal chests work fine with hoppers though

**Comment by broken1arrow** [comment]
> No they throw a huge error in console when they try put something into a wildChests chest. Normal chests work fine with hoppers though
> 
> error: https://pastebin.com/4a5c5qKg

Yeah, i think is because he's change. It will not add any ententes (it will be empty).

**Comment by OmerBenGera** [comment]
Sorry about that, check out latest dev build

**Comment by mike-544** [comment]
Sorry i didnt respond sooner, took a trip and only just got back today. Got this error when placing down storage units : https://pastebin.com/NF2Axusb

Other chests seem to work fine though

**Comment by mike-544** [comment]
Spark Profile: https://spark.lucko.me/c8HAXPWG9M
Everything seemed to work fine, and the usage is much much less but it was also only me online so i could create backups and restore if something went wrong like before. 
I have noticed a new problem however that when i use wildstacker and have a max stack of greater than 64x, it doesn't get picked up properly by the chunkhopper or its not being distributed properly into the large chest.
So i had a max stack of 128x, broke 4 chests full of cactus which should fill up 2 pages of the large chest but it only filled up 1 page and a tiny bit of the 2nd. I am unsure of which plugin is at fault as the chunkhoppers work perfectly fine when going into a normal chest (no items lost) but when they go directly into a large chest (or storage unit) the items get lost.
Imgur link to vid: https://imgur.com/a/sWtdnNX

**Comment by broken1arrow** [comment]
> Spark Profile: https://spark.lucko.me/c8HAXPWG9M Everything seemed to work fine, and the usage is much much less but it was also only me online so i could create backups and restore if something went wrong like before (so none were being used except mine, will have to update this when we get our players back on)
> 
> I have noticed a new problem however that when i use wildstacker and have a max stack of greater than 64x, it doesn't get picked up properly by the chunkhopper or its not being distributed properly into the large chest. So i had a max stack of 128x, broke 4 chests full of cactus which should fill up 2 pages of the large chest but it only filled up 1 page and a tiny bit of the 2nd. I am unsure of which plugin is at fault as the chunkhoppers work perfectly fine when going into a normal chest (no items lost) but when they go directly into a large chest (or storage unit) the items get lost. Imgur link to vid: https://imgur.com/a/sWtdnNX

If your plugin only pick up items to hopper and the hopper self try add items. Should not be issue with chunkhopper . But easy test with normal hopper on top of the chest.

**Comment by OmerBenGera** [comment]
> Spark Profile: https://spark.lucko.me/c8HAXPWG9M Everything seemed to work fine, and the usage is much much less but it was also only me online so i could create backups and restore if something went wrong like before (so none were being used except mine, will have to update this when we get our players back on)
> 
> I have noticed a new problem however that when i use wildstacker and have a max stack of greater than 64x, it doesn't get picked up properly by the chunkhopper or its not being distributed properly into the large chest. So i had a max stack of 128x, broke 4 chests full of cactus which should fill up 2 pages of the large chest but it only filled up 1 page and a tiny bit of the 2nd. I am unsure of which plugin is at fault as the chunkhoppers work perfectly fine when going into a normal chest (no items lost) but when they go directly into a large chest (or storage unit) the items get lost. Imgur link to vid: https://imgur.com/a/sWtdnNX

Not related to this issue in any way.
Test it on a proper server, spark profiler with only you online is not that useful

**Comment by mike-544** [comment]
Sadly because the last updates broke more than they fixed i couldn't trust you enough to test it with people online as it breaks all their chests and makes them unusable. Only way to test it was by doing what i said before where i had to whitelist the server, create a backup and then test it, then restore it back after it fucked things up.
If you could test it yourself first and guarantee it would work without messing things up then i would be able to do it while all my players are online, but im not risking doing it while they are for me to then shutdown the server 15 minutes later losing them their progress in that time.

So until i can see other people using it fine or a personal guarantee from you that the next dev build works fine, i cannot provide you with the spark profiler while all the players are online like normal

**Comment by OmerBenGera** [comment]
> Sadly because the last updates broke more than they fixed i couldn't trust you enough to test it with people online as it breaks all their chests and makes them unusable. Only way to test it was by doing what i said before where i had to whitelist the server, create a backup and then test it, then restore it back after it fucked things up. If you could test it yourself first and guarantee it would work without messing things up then i would be able to do it while all my players are online, but im not risking doing it while they are for me to then shutdown the server 15 minutes later losing them their progress in that time.
> 
> So until i can see other people using it fine or a personal guarantee from you that the next dev build works fine, i cannot provide you with the spark profiler while all the players are online like normal

I have never managed to replicate the issue on my own, even with the old version.
However, it should be fixed.

If you can't trust me, then we can just close this issue for now until the stable version is out.
