### ISSUE TITLE
storage_unit not work

### ISSUE THREAD

**Issue by SkytraceXLSU** [BG-Software-LLC/WildChests#144]
### Minecraft's Version

This server is running Paper version git-Paper-265 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 117579c)
You are 34 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-255 (MC: 1.19.2)

### Plugin's Version

WildChests v2022.7-b83

### Describe the bug

storage_unit not work, when I open have error in console
![image](https://user-images.githubusercontent.com/78903583/204324100-5062d216-c2c0-433f-a03b-49a507514670.png)
![image](https://user-images.githubusercontent.com/78903583/204324240-d627a54d-3a84-4777-853a-c93f9ec70d71.png)

### To Reproduce

don't know

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works.

**Comment by alek4032** [comment]
> Check out latest dev build, let me know if it works.

We had the same issue on our servers, but the latest Dev build resolved it. Thank you!
