### ISSUE TITLE
ShopGUI+ not syncing

### ISSUE THREAD

**Issue by Superalex0102** [BG-Software-LLC/WildChests#148]
### Minecraft's Version

paper 1.12.2

### Plugin's Version

2022.7-b81

### Describe the bug

When I modify the prices of ShopGUI+, WildChests doesn't wanna apply the new prices (it used to apply it instantly after /shop reload)

### To Reproduce

-

**Comment by OmerBenGera** [comment]
You must restart for it to be updated.
WC caches the prices and therefore reloading SGP will not update the prices for WC
