### ISSUE TITLE
Items being sold for less money

### ISSUE THREAD

**Issue by DuneSciFye** [BG-Software-LLC/WildChests#149]
### Minecraft's Version

git-Purpur-1839 (MC: 1.19.2)*

### Plugin's Version

WildChests version 2022.7-b81

### Describe the bug

![image](https://user-images.githubusercontent.com/65089425/207691244-d38a7aaa-a4f3-46db-95d0-848ae6024380.png)
![image](https://user-images.githubusercontent.com/65089425/207691249-c21c4493-93dc-4261-aa2f-004b4100494f.png)
Iron ingots sell for 10. In the sell logs the iron ingots sold for less than 10.

### To Reproduce

Sell a ton of stuff

**Comment by DuneSciFye** [comment]
No I do not have any multiplier

**Comment by SkeletonAce** [comment]
Hi I'm also having this issue, Different players get different amounts displayed (inconsistant) and the totals are always less than it should be. When manually doing the calculation of items to money the totals for money displayed are not correct in the notification.

**Comment by OmerBenGera** [comment]
@DuneSciFye @SkeletonAce Fixed with latest stable/dev build
