### ISSUE TITLE
Selling items with Persistent Data Container - ShopGUIPlus

### ISSUE THREAD

**Issue by Mirayii** [BG-Software-LLC/WildChests#154]
### Minecraft's Version

Purpur 1.19.2 Build 1852

### Plugin's Version

Dev Build 87

### Describe the bug

Items with Persistent Data Container can be sold in Sell Chests and not directly in ShopGUIPlus. This mainly affects servers with Slimefun, where items with Persistent Data Container can be sold. For Example Magnesium Ingot is Iron Ingot, Shop doesn't sell that item, but Sell Chest will.

### To Reproduce

Create an ItemStack with PersistentDataContainer, for example Iron Ingot and try to sell it in ShopGUIPlus. It won't work. Try to put it in Sell Chest and the Sell Chest will sell it with no problem.

**Comment by OmerBenGera** [comment]
In your SGP config, do you have the compare meta option enabled?

**Comment by Mirayii** [comment]
I do not, i'll test it with it enabled. But it seems weird that it doesn't allow to sell it by default with it being false.

**Comment by Mirayii** [comment]
That fixes it, thank you and sorry for bothering.
