### ISSUE TITLE
Slimefun Output Chest being duped due to WildChests blocking placement of chests next to each other

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/WildChests#155]
### Minecraft's Version

purpur dev 1856 1.19.2

### Plugin's Version

Build 87

### Describe the bug

When placing a Slimefun output chest next to a chest from WildChests, it causes the Slimefun output chest to dupe. 

### To Reproduce

https://www.youtube.com/watch?v=D1paz-FwKqM

### Additional Information

I believe the chest needs to check for modified chests as well?

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by Skizzles** [comment]
This is fixed thank you
