### ISSUE TITLE
ShopGUIPlus hook

### ISSUE THREAD

**Issue by lilspojo** [BG-Software-LLC/WildChests#156]
### Minecraft's Version

1.19.3 git-Purpur-1876

### Plugin's Version

2022.7-b87 & 2022.7-b88 

### Describe the bug

The hook into ShopGUIPlus doesnt work since dev build 2022.7-b87, while 2022.7-b86 works perfectly fine. The exact issue is it defaults to the WildChests set item values when set to ShopGUIPlus.

### To Reproduce

1. Use dev build 2022.7-b87 or 2022.7-b88
2. Use the prices-provider ShopGUIPlus
3. Test in-game, it will default to the sell values set in the config.

**Comment by OmerBenGera** [comment]
Do you see "Using ShopGUIPlus as PricesProvider" in console?
Use CTRL+F in your logs file

**Comment by lilspojo** [comment]
Doing that, i find this as a result:
```[13:43:56] [Server thread/INFO]: [WildTools] Loading providers started...
[13:43:56] [Server thread/INFO]: [WildTools]  - Using ShopGUIPlus as PricesProvider.
[13:43:56] [Server thread/INFO]: [WildTools]  - Couldn't find any prices providers, using default one.
[13:43:56] [Server thread/INFO]: [WildTools]  - Couldn't find any factions providers for tnt banks, using default one.
[13:43:56] [Server thread/INFO]: [WildTools] Using Vault as an economy provider.
[13:43:56] [Server thread/INFO]: [WildTools] Loading providers done (Took 15ms)

**Comment by OmerBenGera** [comment]
What version of SGP do you use?

**Comment by OmerBenGera** [comment]
> Couldn't default prices provider

You have your SGP configured as WildChests.

**Comment by lilspojo** [comment]
Thing is, it’s set to ShopGUIPlus in the config, and switching back to b86 works flawlessly, so it’s set properly

**Comment by OmerBenGera** [comment]
> Thing is, it’s set to ShopGUIPlus in the config, and switching back to b86 works flawlessly, so it’s set properly

Upload your config file to pastebin and send it here

**Comment by lilspojo** [comment]
Here’s the pastebin link: https://pastebin.com/0WASb3AG

**Comment by OmerBenGera** [comment]
No clue why it occurs, it works fine for me
Are you sure you have SGP installed and works?

**Comment by lilspojo** [comment]
I do have ShopGUIPlus installed and it does work, reverting to b86 fixed it so it’s clear that ShopGUIPlus itself is fine

**Comment by OmerBenGera** [comment]
Try it on a server with only WildChests and SGP on latest dev build of WC, let me know if it still occurs

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by lilspojo** [comment]
Sorry I forgot about this, and no I don’t have any updates, I am no longer using the plugin, and am using one that better suits my needs.
