### ISSUE TITLE
Coreprotect

### ISSUE THREAD

**Issue by dan28000** [BG-Software-LLC/WildChests#158]
### Minecraft's Version

1.16.5 - purpur

### Plugin's Version

latest dev build

### Describe the bug

when coreprotect is on server and you destroy any wildchest it throws error https://pastebin.com/hJbbAMHA

### To Reproduce

setup latest 1.16.5 purpur server with coreprotect and wildchests
place and destroy wildchest

**Comment by OmerBenGera** [comment]
Try it on Paper, let me know if it still occurs

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by OmerBenGera** [comment]
> still same issue

Send me the error again (the new one that you receive from using latest dev build)

**Comment by dan28000** [comment]
https://pastebin.com/Bfw9ALNg

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works now

**Comment by dan28000** [comment]
yes it works
