### ISSUE TITLE
Enderpearls don't sell

### ISSUE THREAD

**Issue by ArmonicPvP** [BG-Software-LLC/WildChests#159]
### Minecraft's Version

1.19.3 Paper

### Plugin's Version

WildChests b86

### Describe the bug

Ender pearls don't sell in sell chests

### To Reproduce

put enderpearl in sell chest

### Additional Information

https://hastebin.com/tehocufaxe.yaml

Config ^

**Comment by OmerBenGera** [comment]
The hastebin is invalid
Upload it to another service

**Comment by OmerBenGera** [comment]
Does it happen if you use default files of WildChests and ShopGUIPlus?
(Of course, after you changed the prices provider to ShopGUIPlus)

**Comment by OmerBenGera** [comment]
Is this still relevant?
