### ISSUE TITLE
Non stackable items stacking

### ISSUE THREAD

**Issue by DuneSciFye** [BG-Software-LLC/WildChests#161]
### Minecraft's Version

Current: git-Purpur-1876 (MC: 1.19.3)*

### Plugin's Version

WildChests version 2022.7-b89

### Describe the bug

When non stackable items stack due to wildstacker, the stacked version goes into the chests. 
![image](https://user-images.githubusercontent.com/65089425/215925019-bdeecfaf-cc49-46de-8bd2-f4fb6b7ab678.png)
In the image you can see totem of undyings stacking.

### To Reproduce

1. Have an auto collector full
2. Drop a totem of undying
3. Drop another one, this should stack with the first via wildstacker
4. Free up a slot in the auto collector
5. The totem of undyings should show up in that slot, with a stack size of two

### Additional Information

WildStacker version 2022.6-b407

WildChests config: https://pastebin.com/NFi1APid
WildStacker config: https://pastebin.com/hPJJRr6L

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
