### ISSUE TITLE
Reuploading issue of direct link on spigot becuse it was closed without reply

### ISSUE THREAD

**Issue by BLACKoDEMON** [BG-Software-LLC/WildChests#163]
### Minecraft's Version

1.19.2 Spigot

### Plugin's Version

Latest version 

### Describe the bug

Heyy Ome_R sorry for disturbing you. But can you plese give direct download link of WildChests on spigot . Cause there is a server hosting website called aternos and it don't allow plugins with [Download Now
Via external site] so can you plese give direct link insted of your website :(

### To Reproduce

Update the link to direct link on spigot

### Additional Information

![IMG_20230205_223955](https://user-images.githubusercontent.com/124519928/217060475-ff8f0bd2-99dc-4e95-9d9e-201886ca8232.jpg)

**Comment by OmerBenGera** [comment]
Dont use Aternos then...

**Comment by BLACKoDEMON** [comment]
Bruh ....
