### ISSUE TITLE
Economyshopgui not working with wildchests

### ISSUE THREAD

**Issue by Oddengineers** [BG-Software-LLC/WildChests#164]
### Minecraft's Version

1.19.4 paper server

### Plugin's Version

WildChests-2022.7-b92
EconomyShopGUI-5.3.0

### Describe the bug

The sell chest does not recognize Economyshopgui sell prices when i set the prices-provider: to it but when i switch to Wildchests price provider and add the items into config file thats when it sells the contents for the price i set. Just to note yes i checked to make sure the item was in Economyshopgui sell list and that there was a set sell price on it. 

### To Reproduce

make price-provider: Economyshopgui with the latests build and see if chest sells in 10 second intervals nothing happens  then switch to wildchest price provider and make sure item selling is part of the wildchest pricing and the sellchest starts selling.

**Comment by OmerBenGera** [comment]
It works fine for me.
I have latest dev build of WildChests as well as latest version of EconomyShopGUI.
I put "EconomyShopGUI" in the config file for the prices provider, then sold diamonds in a sell chest and I received the money.

Do you see "Using EconomyShopGUI as PricesProvider" message in your console? You should see one from when the plugin loaded.

**Comment by Oddengineers** [comment]
Ya it showed in consol using economyshopgui as price provider could it be the value is set to low for the plugin to recognize? It is set to like 0.13 ill try to increase it if that's the issue if not what would be the next step?

**Comment by OmerBenGera** [comment]
Does it still occur?

**Comment by OmerBenGera** [comment]
Is this still relevant?

**Comment by Oddengineers** [comment]
As far as I know its still good after the changes we made but id have to look and verify

Sent from Yahoo Mail on Android 
 
  On Fri, Jun 23, 2023 at 4:22 AM, ***@***.***> wrote:   


Is this still relevant?

**Comment by OmerBenGera** [comment]
I am closing this as it seems to be fixed
If the issue continues let me know
