### ISSUE TITLE
Notifier needs a check

### ISSUE THREAD

**Issue by Superalex0102** [BG-Software-LLC/WildChests#165]
### Minecraft's Version

1.18.2 paper

### Plugin's Version

b81

### Describe the bug

![image](https://user-images.githubusercontent.com/41546701/226173878-f20f3fd7-5216-4de0-a8d1-a9d8cf694c0e.png)

So the notifier feature has 2 major bugs currently.

1) The amount that it says is always a lower value than the actual one (maybe because of ShopGUI's modifiers?)
2) The same item is somehow written multiple times as "x64", in this case it's written twice.

Can you please look into these?

### To Reproduce

-

**Comment by OmerBenGera** [comment]
1. The amount being displayed is identical to the amount deposited by WildChests. Therefore, if SGP or any other plugin deposited additional money, it will not be seen here.
2. The same item is displayed, which makes me believe the items were not identical. I think it happens if you sell two items with different name, for example. Can you confirm/deny it?

**Comment by Superalex0102** [comment]
1. I don't get any money from anywhere else I even tested this on my test server
2. The item is blank with no names at all and it does this with every spawner type I have tested so far

**Comment by OmerBenGera** [comment]
About the second bug, open a new issue regarding this, and we'll focus on the first bug in this report.
Let me know how to replicate the issue - what items to put in the sell chest, etc.
Make sure you use default config files for all the plugins you use.

**Comment by Superalex0102** [comment]
I will make an issue for the second bug. On this video both of the bugs occured. I used default config of WildStacker and WildChests, the only changes I made is shown on the video.

On my public server I use a 5 minute notifier interval and the difference is huge, but even with a 1 minute notifier there is a noticeable difference.

https://youtu.be/-vK0d5P_RQw

**Comment by OmerBenGera** [comment]
Sell items individually by putting them in the sell chest.
Let me know if you can replicate the issue.

**Comment by Superalex0102** [comment]
![image](https://user-images.githubusercontent.com/41546701/227713373-9baf3b7d-698e-4bbc-bb1c-49bcf84cdbfe.png)
Yep still occurs, the difference is huge.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it's better.

**Comment by Superalex0102** [comment]
Works, ty
