### ISSUE TITLE
server crashing

### ISSUE THREAD

**Issue by SrMonsterYT** [BG-Software-LLC/WildChests#166]
### Minecraft's Version

git-Pufferfish-47 (MC: 1.19.2)

### Plugin's Version

WildChests-2022.7-b91.jar

### Describe the bug

I could not find the problem but 1 player joined and the server crashed

error: https://pastebin.com/MLJqderd

### To Reproduce

don't know yet

**Comment by OmerBenGera** [comment]
Your server lagged out.
Take a timings report and check what causes lag on your server.

**Comment by SrMonsterYT** [comment]
https://timings.aikar.co/dev/?id=a56d5c1806f84e28b5e827e0ec230142
everything was normal until I updated the wildchests

**Comment by OmerBenGera** [comment]
WildChests looks totally fine in your timings report.
Why do you think it's WildChests..?

**Comment by SrMonsterYT** [comment]
> WildChests looks totally fine in your timings report. Why do you think it's WildChests..?

again only now it has dropped some players, and everything shows wildchests  

erro: https://pastebin.com/xkHePnMX

**Comment by OmerBenGera** [comment]
It happened when opening a chest of wildchest, it dpesnt mean its an issue of WildChests.
As I said, your server just lags out. When the TPS is low, take a timings report so we can find the cause of it.

**Comment by OmerBenGera** [comment]
Then investigate the issue and find out what causes this to occur.

**Comment by SrMonsterYT** [comment]
I have a plugin that sends all items from wildstacker to wildschests automatically, if it has 20k items it sends them all at once, I think that's what it is because I already did a test like this on the test server

here is the error that happened again:    

https://mclo.gs/5e2K9gj

**Comment by SrMonsterYT** [comment]
I managed to replicate the bug here: 

video: https://youtu.be/iRBOu-4QHes
error console: https://mclo.gs/cRKKD3O
image: https://prnt.sc/344Y49U_T436

I put 10 million mobs and killed, and the system sent the 10kk mobs to wildchests, and the error happened in the console, some of my players have 1k mobspawners blaze and leave accumulating enough I think it may be that I can not say more I have seen players with 5kk mobs grouped

wildschests version: WildChests-2023.1-b97.jar
wildstacker version: WildStacker-2023.1-b425.jar

server version git-Pufferfish-42 (MC: 1.19.2)

**Comment by OmerBenGera** [comment]
Show me the code of your plugin.
Upload it to pastebin and send a link to it here.

**Comment by SrMonsterYT** [comment]
> Show me the code of your plugin. Upload it to pastebin and send a link to it here.

https://mclo.gs/YOYy6Fw

**Comment by OmerBenGera** [comment]
> > Show me the code of your plugin. Upload it to pastebin and send a link to it here.
> 
> https://mclo.gs/YOYy6Fw

What is the type of chest that you add the items to?

**Comment by SrMonsterYT** [comment]
> 

wildchests config: https://pastebin.com/kbhDbKQW

**Comment by OmerBenGera** [comment]
So you add a lot of items into a storage unit at once?
That what causes the lag? or opening the storage unit later?

**Comment by SrMonsterYT** [comment]
> https://youtu.be/iRBOu-4QHes

if I send 1kk - 10kk items it brings down the server

**Comment by OmerBenGera** [comment]
> > https://youtu.be/iRBOu-4QHes
> 
> if I send 1kk - 10kk items it brings down the server

When does it happen?
When you add the items or when opening the chest?

**Comment by SrMonsterYT** [comment]
> 

when the items are sent to the chest, in the video it shows as soon as the items were pulled the server crashed

**Comment by OmerBenGera** [comment]
Try it on a server with only WildChests and WildStacker installed, check if it still occurs.

**Comment by OmerBenGera** [comment]
Do you add your items all in one, or you add them stack by stack?

**Comment by SrMonsterYT** [comment]
> Do you add your items all in one, or you add them stack by stack?

I don't understand what you mean, but the collector sent all the items to the wildchests, can you tell me if I can make him send only 10k in 10k no matter how many items are on the floor? he sends 10k in 10k every 1 second?

**Comment by OmerBenGera** [comment]
> > Do you add your items all in one, or you add them stack by stack?
> 
> I don't understand what you mean, but the collector sent all the items to the wildchests, can you tell me if I can make him send only 10k in 10k no matter how many items are on the floor? he sends 10k in 10k every 1 second?
> 
> isn't there a way to fix the wildchests of receiving that many items without crashing the server?

I don't know how you send the items to the chest.
Do you send them stack by stack, or send them to the chest all in once?

I suspect the issue is not related to WildChests, but your code. I suspect you try to add the large amount of items stack by stack, making the server freezing as there are tons of stacks in that amount of items.
If you'll only use WildChests and WildStacker, you'll see that the chunk collector feature of WildChests can handle this amount in no problem. It is something with your plugin that causing it, and I suspect it's something related to your code and not WildChests'.

**Comment by SrMonsterYT** [comment]
> > > Do you add your items all in one, or you add them stack by stack?
> > 
> > 
> > I don't understand what you mean, but the collector sent all the items to the wildchests, can you tell me if I can make him send only 10k in 10k no matter how many items are on the floor? he sends 10k in 10k every 1 second?
> > isn't there a way to fix the wildchests of receiving that many items without crashing the server?
> 
> I don't know how you send the items to the chest. Do you send them stack by stack, or send them to the chest all in once?
> 
> I suspect the issue is not related to WildChests, but your code. I suspect you try to add the large amount of items stack by stack, making the server freezing as there are tons of stacks in that amount of items. If you'll only use WildChests and WildStacker, you'll see that the chunk collector feature of WildChests can handle this amount in no problem. It is something with your plugin that causing it, and I suspect it's something related to your code and not WildChests'.

my plugin: https://mclo.gs/YOYy6Fw

**Comment by OmerBenGera** [comment]
> > > > Do you add your items all in one, or you add them stack by stack?
> > > 
> > > 
> > > I don't understand what you mean, but the collector sent all the items to the wildchests, can you tell me if I can make him send only 10k in 10k no matter how many items are on the floor? he sends 10k in 10k every 1 second?
> > > isn't there a way to fix the wildchests of receiving that many items without crashing the server?
> > 
> > 
> > I don't know how you send the items to the chest. Do you send them stack by stack, or send them to the chest all in once?
> > I suspect the issue is not related to WildChests, but your code. I suspect you try to add the large amount of items stack by stack, making the server freezing as there are tons of stacks in that amount of items. If you'll only use WildChests and WildStacker, you'll see that the chunk collector feature of WildChests can handle this amount in no problem. It is something with your plugin that causing it, and I suspect it's something related to your code and not WildChests'.
> 
> my plugin: https://mclo.gs/YOYy6Fw

Where do you add the items exactly? Line 168?

**Comment by SrMonsterYT** [comment]
> > > > > Do you add your items all in one, or you add them stack by stack?
> > > > 
> > > > 
> > > > I don't understand what you mean, but the collector sent all the items to the wildchests, can you tell me if I can make him send only 10k in 10k no matter how many items are on the floor? he sends 10k in 10k every 1 second?
> > > > isn't there a way to fix the wildchests of receiving that many items without crashing the server?
> > > 
> > > 
> > > I don't know how you send the items to the chest. Do you send them stack by stack, or send them to the chest all in once?
> > > I suspect the issue is not related to WildChests, but your code. I suspect you try to add the large amount of items stack by stack, making the server freezing as there are tons of stacks in that amount of items. If you'll only use WildChests and WildStacker, you'll see that the chunk collector feature of WildChests can handle this amount in no problem. It is something with your plugin that causing it, and I suspect it's something related to your code and not WildChests'.
> > 
> > 
> > my plugin: https://mclo.gs/YOYy6Fw
> 
> Where do you add the items exactly? Line 168?

I changed the code now it pulls 100k in 100k, but still the  wildchests gives some strange bug, well the problem is on the side of wildchests, I have another plugin here, which is called superhoppers and does not happen this

video: -> https://youtu.be/jHrnVlqEH84 
see when millions of items are going into the funnel and this doesn't happen

**Comment by OmerBenGera** [comment]
> 

I dont understand what the bug is from your video; you dont use anything from wildchests

**Comment by SrMonsterYT** [comment]
> > 
> 
> I dont understand what the bug is from your video; you dont use anything from wildchests

the video only shows that it is possible to send millions of items to 1 storage without affecting the server, but if I send millions of items to wildchests it crashes the server

**Comment by OmerBenGera** [comment]
You said WildChests is having "a strange bug" but you have never mentioned what the bug is.
Did you meant that it keeps crashing the server?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Is this still relevant?

**Comment by SrMonsterYT** [comment]
the problem was in BottledExp when players got xp in jar dropped a lot of items and wildstacker could not account for grouping making the server crash.

**Comment by OmerBenGera** [comment]
What is BottledExp..?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues let me know
