### ISSUE TITLE
Notifier shows items multiple times

### ISSUE THREAD

**Issue by Superalex0102** [BG-Software-LLC/WildChests#167]
### Minecraft's Version

1.18.2 paper

### Plugin's Version

b81

### Describe the bug

The same item is somehow written multiple times as "x64", in this case it's written twice.
![image](https://user-images.githubusercontent.com/41546701/227708337-3832686f-74e3-4de0-9da6-b862e684023f.png)

### To Reproduce

https://www.youtube.com/watch?v=-vK0d5P_RQw

**Comment by OmerBenGera** [comment]
As I said in the other report, put items in the sell chest individually, check if it still occurs

**Comment by Superalex0102** [comment]
![image](https://user-images.githubusercontent.com/41546701/227712785-60b452aa-3add-4e0e-a66b-25e026f04311.png)
Yep, still happens

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it's better.

**Comment by Superalex0102** [comment]
Works, ty
