### ISSUE TITLE
Bug with rosestacker 

### ISSUE THREAD

**Issue by RoyalMagmaa** [BG-Software-LLC/WildChests#172]
### Minecraft's Version

1.18.2

### Plugin's Version

Last

### Describe the bug

stacker-provider is configured on RoseStacker when I put a sell chest with the option that collects within a certain radius, if I have for example 500k items there are 3456 that are collected and sold and the excess is deleted

### To Reproduce

just a big stack of items with sellchest with the option collects in radius

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by RoyalMagmaa** [comment]
With the latest version (2023.1-b1) stacks of more than 3456 items are no longer destroyed but the sell chests no longer sell the items if there is the auto-suction option

**Comment by RoyalMagmaa** [comment]
With the latest version (2023.1-b1) stacks of more than 3456 items are no longer destroyed but the sell chests no longer sell the items if there is the auto-suction option, but also the item values ​​do not are not well updated so if I have 100k of items the sell chest with the auto-suction recover option recovers infinitely many items

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works now

**Comment by OmerBenGera** [comment]
I am closing this for now.
If the issue persists let me know
