### ISSUE TITLE
AutoSell Chest is not working while the player is offline

### ISSUE THREAD

**Issue by Superalex0102** [BG-Software-LLC/WildChests#175]
### Minecraft's Version

1.18.2

### Plugin's Version

2023.1-b4

### Describe the bug

I updated to the latest (2023.1-b4) version and the offline autosell stopped working, can you check on this?

### To Reproduce

-

**Comment by OmerBenGera** [comment]
As long as your economy plugin supports depositing money to offline players and that the chest is in a loaded chunk, sell chests will deposit money to offline players.

**Comment by OmerBenGera** [comment]
What is your prices provider?

**Comment by Superalex0102** [comment]
ShopGUI+ 1.81.3

**Comment by OmerBenGera** [comment]
@Superalex0102 Check out latest dev build, let me know if it works.

**Comment by OmerBenGera** [comment]
I am closing this for now
If the issue persists let me know
