### ISSUE TITLE
Crash on load chunk

### ISSUE THREAD

**Issue by Xitryne** [BG-Software-LLC/WildChests#176]
### Minecraft's Version

Paper 1.17.1

### Plugin's Version

WildChests-2023.1-b5.jar

### Describe the bug

I have the SuperiorSkyblock plugin with Advanced Slime World Manager, when I reach an island that contains a WildChests plugin chest, (after having fully unloaded the island), when I reach the server it crashes when loading the chests.

### To Reproduce

Install SuperiorSkyblock, link it with ASWM
Installing a WildChests chest
Disconnect until the island is completely unloaded
Reconnect and crash when loading island

### Additional Information

https://pastes.io/e9ebgvgm3w

**Comment by OmerBenGera** [comment]
For no reason, when ChunkLoadEvent is called and WildChests calls Location#getBlock, it causes a deadlock.
Contact the AdvancedSlimeWorldManager author for help with that, as this is a bug with ASWM and not WildChests nor SuperiorSkyblock.
