### ISSUE TITLE
WildChestsAPI#getStorageChest throws ClassCastException instead of returning null

### ISSUE THREAD

**Issue by mfnalex** [BG-Software-LLC/WildChests#178]
### Minecraft's Version

Spigot 1.19

### Plugin's Version

2023.1-b5

### Describe the bug

Using WildChestsAPI#getStorageChest on a chest that's not a storage chest, but e.g. a linked chest, throws a ClassCastException instead of returning null - so either there's a bug in the code, or the API docs are wrong ( https://bg-software.com/wildchests/api/com/bgsoftware/wildchests/api/WildChestsAPI.html#getStorageChest-org.bukkit.Location- claims it returns null if it's not a storage chest ).

For a full stacktrace, see issue #177. The line in my code (WildChestsHook line 25) looks like this:

```java
StorageChest storageChest = WildChestsAPI.getStorageChest(event.getBlock().getLocation());
```

### To Reproduce

Use WildChestsAPI#getStorageChest on a chest that is a linked chest

### Additional Information

This is related to issue #177 which unfortunately was closed without any useful reply.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build, sorry about that.
