### ISSUE TITLE
Slime balls and maga cream do not sell

### ISSUE THREAD

**Issue by Trickyricky89** [BG-Software-LLC/WildChests#179]
### Minecraft's Version

minecraft version 1.19.4
paper

### Plugin's Version

used build 2023.1
and dev build 2023.1-b5

### Describe the bug

i place slime balls in the sell chest. close the chest and there still there.
same with maga cream 

### To Reproduce

i explained above about it. i reached out to discord but no help.

### Additional Information

can see in discord this problem was reported in 2021, i would love an update on this please

**Comment by OmerBenGera** [comment]
What plugin are you using for handling your prices within WildChests?

**Comment by Trickyricky89** [comment]
im using ShopGUIPlus

**Comment by OmerBenGera** [comment]
Is this still relevant?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
If the issue continues let me know
