### ISSUE TITLE
EconomyShopGUI bug

### ISSUE THREAD

**Issue by ItzAndriss** [BG-Software-LLC/WildChests#182]
### Minecraft's Version

1.18.2

### Plugin's Version

2023.1

### Describe the bug

the sell chest does not work with the EconomyShopGUI plugin

### To Reproduce

- Set the config file.
- Place the chest

**Comment by OmerBenGera** [comment]
What happens when you have items in the chest?
Does WildChests prompts to console that it hooked into EconomyShopGUI?

**Comment by ItzAndriss** [comment]
No, it does not send anything related to EconomyShopGUI.
![image](https://github.com/BG-Software-LLC/WildChests/assets/81358652/413f8425-bc17-419f-87bf-439a6d27d191)

**Comment by OmerBenGera** [comment]
Please send me your entire logs file.
Upload it to pastebin and send a link to it here.

**Comment by OmerBenGera** [comment]
Try updating WildChests, let me know if it helps.

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues let me know
