### ISSUE TITLE
Stacking unstackable items via storage chest

### ISSUE THREAD

**Issue by DuneSciFye** [BG-Software-LLC/WildChests#183]
### Minecraft's Version

Current: git-Purpur-1876 (MC: 1.19.3)*

### Plugin's Version

WildChests version 2023.1

### Describe the bug

Breaking a storage chest with multiple unstackable items gives you the unstackable items in one stack

### To Reproduce

Place storage chest
Put multiple totems of undying in it
Break chest

### Additional Information

https://github.com/BG-Software-LLC/WildChests/assets/65089425/be6915b0-3f96-4a26-a290-59baf256c00b

**Comment by OmerBenGera** [comment]
I cannot replicate the issue myself.
Are you able to replicate it on a server with only WC installed?

**Comment by DuneSciFye** [comment]
I believe it's a thing with WildStacker and not WC.

**Comment by DuneSciFye** [comment]
Since it works with any chest. Should I move this to WS's github?

**Comment by OmerBenGera** [comment]
If thats WS, then look for the `fix-stack` section.
For further questions, ask on our discord server
