### ISSUE TITLE
Issue with latest version of EconomyShopGUI

### ISSUE THREAD

**Issue by alek4032** [BG-Software-LLC/WildChests#184]
### Minecraft's Version

Minecraft version: 1.20.1
Server Jar: Pufferfish+ 1.20.1 BUILD# 3

### Plugin's Version

Dev Build #7 from 17/06/2023

### Describe the bug

WildChests and EconomyShopGUI cause issues with them both running the latest version, that stops things from being sold. 

![1d4557bd12864fa063ef7c5349adb995](https://github.com/BG-Software-LLC/WildChests/assets/119686785/4a77c6c2-b1ee-4daa-a207-5769d5c1d746)

We get that error in the console and we also spoke with the Dev of EconomyShopGUI that said the following:

![image](https://github.com/BG-Software-LLC/WildChests/assets/119686785/e047758e-b984-44ca-b330-ad4a2b39b981)

### To Reproduce

Install latest version of EconomyShopGUI with Wildchests, place a sellchest and try to sell. 

### Additional Information

Let me know if you need any further info!

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
