### ISSUE TITLE
Doesn’t log in Core Protect

### ISSUE THREAD

**Issue by mrunningmasterc** [BG-Software-LLC/WildChests#185]
### Minecraft's Version

Purpur git-1985

### Plugin's Version

2023.2

### Describe the bug

It doesn’t log into core protect and when players put stuff in and out of chests

### To Reproduce

Place stuff in wild chests and check core protect inspect and it won’t show that you placed or removed stuff from chests. There should be a way to hook into core protect

**Comment by OmerBenGera** [comment]
CoreProtect is not supported, and this is not considered a bug.
You can ask for support to be added by creating a feature request.
