### ISSUE TITLE
Wild Chests randomly deleting chests

### ISSUE THREAD

**Issue by mrunningmasterc** [BG-Software-LLC/WildChests#187]
### Minecraft's Version

Current: git-Purpur-1985 (MC: 1.19.4)*

### Plugin's Version

2023.2

### Describe the bug

Players wild chests items and such are being randomly deleted

### To Reproduce

Put stuff in wild chests and wait a while and it'll be randomly deleted.

### Additional Information

<img width="526" alt="Screen Shot 2023-07-01 at 3 10 56 PM" src="https://github.com/BG-Software-LLC/WildChests/assets/63335629/a830996e-5180-4c78-a01c-99b5c5ad3957">

The photo here shows it being empty, but it was full of stuff. Same for the bottom chest.

**Comment by mrunningmasterc** [comment]
It seems like its large chests right now that are deleting everyone's items.

**Comment by OmerBenGera** [comment]
Check if the contents of the chest exist in the DB.

**Comment by mrunningmasterc** [comment]
<img width="841" alt="Screen Shot 2023-07-10 at 10 45 36 PM" src="https://github.com/BG-Software-LLC/WildChests/assets/63335629/82902e5e-46b3-4d93-9534-942453cff7d1">
<img width="1680" alt="Screen Shot 2023-07-10 at 10 46 22 PM" src="https://github.com/BG-Software-LLC/WildChests/assets/63335629/3b1833f2-0de4-4d81-9c4d-b692aedff04c">

here's the info on that

**Comment by mrunningmasterc** [comment]
<img width="329" alt="Screen Shot 2023-07-10 at 10 47 32 PM" src="https://github.com/BG-Software-LLC/WildChests/assets/63335629/a347f88e-b0b8-454f-8571-61b0273da6b7">

**Comment by OmerBenGera** [comment]
Look for errors when data was loaded from WildChests in the console logs.

**Comment by mrunningmasterc** [comment]
No there isn't any console errors

**Comment by OmerBenGera** [comment]
Chest data is loaded as soon as the chunk is loaded.
Unless something breaks the event from being called, there's no reason for the data to not be loaded.

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues let me know
