### ISSUE TITLE
QuantumShop to ExcellentShop

### ISSUE THREAD

**Issue by WanderSpec** [BG-Software-LLC/WildChests#190]
### Minecraft's Version

Purpur 1.19.4 

### Plugin's Version

2023.2 version

### Describe the bug

Putting QuantumShop in prices provider now doesn't work maybe because of the plugin rename the QuantumShop plugin got renamed to ExcellentShop.

### To Reproduce

putting the QuantumShop on the price provider

**Comment by WanderSpec** [comment]
Can you also please update it for WildTools

**Comment by OmerBenGera** [comment]
I will add support for ExcellentShop in the near future - I contacted their author, hopefully he will respond soon.

**Comment by WanderSpec** [comment]
Thank you very much!

**Comment by WanderSpec** [comment]
Is there a ETA for this update?

**Comment by OmerBenGera** [comment]
Added in latest dev build
