### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by DuneSciFye** [BG-Software-LLC/WildChests#191]
### Minecraft's Version

This server is running SlimeWorldManager version git-SlimeWorldManager-15186 (MC: 1.20.1) (Implementing API version 1.20-R0.1-SNAPSHOT) (Git: 082d551 on paper_upstream)

### Plugin's Version

WildChests version 2023.2

### Describe the bug

Server crashes when player joins at times, something with WildChests causing async chunk load. Started happening when I installed SlimeWorldManager, so must be an incompatbility with SWM

### To Reproduce

Unsure

### Additional Information

https://pastebin.com/a2dsZjgz

**Comment by OmerBenGera** [comment]
Report it to your slime world plugin, not related to WildChests.
WildChests listens to the chunk load event and tries to get a block from the chunk, which somehow causes a deadlock between threads.
