### ISSUE TITLE
Storage Unit Glass Pane Bug

### ISSUE THREAD

**Issue by NiceKaleido** [BG-Software-LLC/WildChests#193]
### Minecraft's Version

MC: 1.20.1
Paper: #84 

### Plugin's Version

Tried the latest stable build as well as the current dev build (b13)

### Describe the bug

When placing a freshly Storage Unit it already holds Black Stained Glass Panes which can be taken out. This also results in Storage Units not functioning properly and spitting out items when opening. 

### To Reproduce

Place a storage unit. take out black stained glass pane. Try to fill it either by hand or hopper

### Additional Information

Here's a short clip of the bug: https://www.youtube.com/watch?v=aSNfVszzQPk

**Comment by broken1arrow** [comment]
Ts did not update this issue. What he wrote on discord was this plugin  https://www.spigotmc.org/resources/jukebox-extended-reborn-add-custom-music-discs.103219/ the issue. 

See if he replay back here.

**Comment by OmerBenGera** [comment]
This doesn't happen for me.
Probably due to the plugin you mentioned above. I'd recommend testing it with only WC installed, check if it still occurred.

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues let me know
