### ISSUE TITLE
ShopGUI+ Durability Selling not working

### ISSUE THREAD

**Issue by ReclinesMC** [BG-Software-LLC/WildChests#194]
### Minecraft's Version

Purpur 1.20.1 b2017

### Plugin's Version

2023.2

### Describe the bug

If I enable ignoring the durability in ShopGUI+'s config, any item with durability will sell fine in the shop, and in their SellGUI expansion, but the sell chest will not sell it.

### To Reproduce

Try putting a stone sword w/ durability in a sell chest with ShopGUI's config set to ignore durability, it will not sell.

**Comment by OmerBenGera** [comment]
Update WildChests to its latest dev build, let me know if it still occurs.

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues let me know
