### ISSUE TITLE
duplication bug

### ISSUE THREAD

**Issue by Naunau99** [BG-Software-LLC/WildChests#198]
### Minecraft's Version

Serveur version : 1.17.2

### Plugin's Version

WildChests-2023.2

### Describe the bug

When a player opens their storage unit and presses shift + left click on an item, there is a chance that the items in the storage unit will all turn into the item that was spammed in the player's inventory. player. The bug succeeds very rarely and with a higher probability when the player has just connected to the server a short time before.

### To Reproduce

Opens their storage unit and presses shift + left click on an item

### Additional Information

https://cdn.discordapp.com/attachments/1046168624701915206/1136610017324306510/2023-08-03_12-40-56.mp4

record of a player who made the bug.

**Comment by OmerBenGera** [comment]
Upload the video to YT or any other streaming service and send a link to it here.

**Comment by Naunau99** [comment]
https://youtu.be/XjizUR-vhVk

**Comment by Naunau99** [comment]
another one video https://www.youtube.com/watch?v=KyaI2rG15DU

**Comment by Naunau99** [comment]
Would it be possible to put this post in private because I have a server open at the moment hosting 300-400 players per day and I do not want them to come across the videos explaining how to reproduce it?

**Comment by OmerBenGera** [comment]
You can make the videos private and share them with whoever you'd like.

Does it happen on a server with only WildChests installed?

**Comment by Naunau99** [comment]
This is the only plugin impacting chests, we don't have any other chest plugins or modifying chests. The bug happens really often and the most when the chunk or is the chest is unloaded and reloaded but it also happens randomly.

**Comment by Naunau99** [comment]
For those of your plugins we also have wildstacker and wildloader on one of our servers.

**Comment by Naunau99** [comment]
We redid a lot of tests and it comes from a recent version of your plugin, the bug occurs when a storage unit has not been loaded for a while, the number remains displayed but the item becomes invisible and at this time the item put in will be duplicated.

**Comment by Naunau99** [comment]
For example I put 5000 carrots I unload the chunk for 30 minutes and I come back the quantity will be displayed in the storage chest but not the item no and at this time I could put the item that I want duplicated.

**Comment by Naunau99** [comment]
We are currently with devs to try to fix the bug but we don't have your way of doing things and your way of thinking.

**Comment by OmerBenGera** [comment]
> For example I put 5000 carrots I unload the chunk for 30 minutes and I come back the quantity will be displayed in the storage chest but not the item no and at this time I could put the item that I want duplicated.

What do you mean by "the quantity will be displayed in the stoage chest but not the item"?
Can you take a screenshot or give more information regarding this?

**Comment by OmerBenGera** [comment]
> For example I put 5000 carrots I unload the chunk for 30 minutes and I come back the quantity will be displayed in the storage chest but not the item no and at this time I could put the item that I want duplicated.

What do you mean by "the quantity will be displayed in the stoage chest but not the item"?
Can you take a screenshot or give more information regarding this?

> We are currently with devs to try to fix the bug but we don't have your way of doing things and your way of thinking.
Huh?
I am making sure there are no other plugins affecting it so we can narrow down what exactly causes the issue, and to make sure it is indeed in the WildChests mechanisms and not other plugin somehow conflicts with it.

**Comment by OmerBenGera** [comment]
Is this still relevant?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
If the issue continues let me know
