### ISSUE TITLE
ExcellentShop Minor API changes. Shop Bridge Issue

### ISSUE THREAD

**Issue by ItzRenzo** [BG-Software-LLC/WildChests#202]
### Minecraft's Version

Purpur 1.20.1

### Plugin's Version

Wild Chest 2023.2-b11

### Describe the bug

Minor API changes to ExcellentShop now the chest won't work and sell wands doesn't work. Here is the error https://pastebin.com/nydd5LpX

### To Reproduce

Trying to sell using sell wand and sell chest

**Comment by OmerBenGera** [comment]
Fixed with latest dev build
