### ISSUE TITLE
Error with custom head

### ISSUE THREAD

**Issue by titidelaff** [BG-Software-LLC/WildChests#207]
### Minecraft's Version

paper 1.20.1

### Plugin's Version

WildChests-2023.2-b19

### Describe the bug

https://pastebin.com/yRSJFfqg

### To Reproduce

Use EconomyShopGui as provider.
Insert custom head into sell chest.

**Comment by OmerBenGera** [comment]
Contact EconomyShopGUI regarding this, as it is not related to WildChests.
