### ISSUE TITLE
Chests not loading

### ISSUE THREAD

**Issue by DuneSciFye** [BG-Software-LLC/WildChests#208]
### Minecraft's Version

This server is running SlimeWorldManager version git-SlimeWorldManager-15186 (MC: 1.20.1) (Implementing API version 1.20-R0.1-SNAPSHOT) (Git: 082d551 on paper_upstream)

### Plugin's Version

WildChests version 2023.2

### Describe the bug

Ever since I updated SS2 and the islands aren't loaded on startup anymore, WildChests custom chests don't load. While they aren't deleted from the database, they also don't load when a player joins the server and his island loads. My minions plugin also had this issue and it was resolved by "removing world loaded check while loading minions"

If that could be changed and the console error message for null world could be removed, either by default or a config option, that would be terrific!

![image](https://github.com/BG-Software-LLC/WildChests/assets/65089425/b5384248-d368-4c38-91c9-8ebce8e0922a)

### To Reproduce

1. Use SS2, SlimeWorldManager, WildChests
2. Make an island
3. Place down custom chest from WildChests
4. Restart the server

**Comment by DuneSciFye** [comment]
I believe this is a SS2-ASWM addon issue. SS2 needs to call the WorldLoadEvent, which should fix this and other plugins that are experiencing the same issue.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works
