### ISSUE TITLE
SellChest disappears when it gets dropped into hopper

### ISSUE THREAD

**Issue by Pjooo** [BG-Software-LLC/WildChests#209]
### Minecraft's Version

1.20.1 Purpur-2062

### Plugin's Version

2023.2

### Describe the bug

When SellChest is dropped into hopper it just disappears. It's not inside hopper, it just vanishes.

### To Reproduce

Put sellchest into hopper.

**Comment by OmerBenGera** [comment]
Try it on a server with only WildChests installed.
Let me know if it still occurs

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues let me know
