### ISSUE TITLE
Server Crash on ChunkLoadEvent

### ISSUE THREAD

**Issue by DuneSciFye** [BG-Software-LLC/WildChests#210]
### Minecraft's Version

This server is running SlimeWorldManager version git-SlimeWorldManager-15186 (MC: 1.20.1) (Implementing API version 1.20-R0.1-SNAPSHOT) (Git: 082d551 on paper_upstream)

### Plugin's Version

SuperiorSkyblock2 version .2

### Describe the bug

Ever since I've switched to ASWM/SWM/ASP, I've been having some issues with chunks and plugins.

I've contacted multiple devs to try and fix issues, and I've contacted the devs of ASP, and I've got a large portion of the issues out of the way, the only ones being these two:
WildChests crashes the server when a player joins. This only happened occasionally, but it's consistent.

"I don't know for sure but there is something wrong in chunk loading. Plugins think that specific chunk is loaded but in reality it is either not loaded or loaded and unloaded 1 second later"

Second issue is that minions from minions plugins randomly disappear. At first they wouldn't load at all, but I've got that issue fixed. Now, the armor stands will disappear, but they are still there and later randomly reappear.

### To Reproduce

Place WildChests in SS2 Slime World Island
Restart server
Join server

### Additional Information

[2023-09-04-1.log.gz](https://github.com/BG-Software-LLC/SSB-SlimeWorldManager/files/12561838/2023-09-04-1.log.gz)

**Comment by OmerBenGera** [comment]
Update WildChests, let me know if the issue still occurs
