### ISSUE TITLE
Server Crashes on Joining

### ISSUE THREAD

**Issue by DuneSciFye** [BG-Software-LLC/WildChests#211]
### Minecraft's Version

This server is running SlimeWorldManager version git-SlimeWorldManager-15186 (MC: 1.20.1) (Implementing API version 1.20-R0.1-SNAPSHOT) (Git: 082d551 on paper_upstream)

### Plugin's Version

WildChests version 2023.3

### Describe the bug

When some players join, the server crashes basically every time. If they join back right after the server starts back up after the crash, it works fine.

### To Reproduce

NA

### Additional Information

https://pastebin.com/gNc8Qm6U

**Comment by OmerBenGera** [comment]
This is related to the slime world manager jar that you use, not WildChests.
What makes you believe it is related to WildChests?

**Comment by OmerBenGera** [comment]
Report it over SlimeWorldManager's authors.
WildChests tries to read data from the chunk in ChunkLoadEvent and this causes the server to crash.
It works fine on Spigot & Paper, therefore it is not related to WildChests directly.

**Comment by DuneSciFye** [comment]
Could you add a delay to the chests loading?

**Comment by DuneSciFye** [comment]
Could you add the delay made by this fork: https://github.com/WaterArchery/WildChests

**Comment by OmerBenGera** [comment]
That developer does not check if the chunk is still loaded, which can cause the chunk to load again.

**Comment by DuneSciFye** [comment]
Well is there any way of delaying it to make it work with SWM?

**Comment by DuneSciFye** [comment]
I'm willing to pay for some sort of configuration or anything.

**Comment by DuneSciFye** [comment]
This is still happening: https://pastebin.com/Qx6BE8fa
Please help

**Comment by DuneSciFye** [comment]
![image](https://github.com/BG-Software-LLC/WildChests/assets/65089425/cf7e2a61-ee36-4434-a631-c49de143bbd6)


https://github.com/BG-Software-LLC/WildChests/blob/713e2c636b95d49c85712e14e812f23b711bbcc6/src/main/java/com/bgsoftware/wildchests/listeners/ChunksListener.java#L35

**Comment by OmerBenGera** [comment]
As I said, you should report it over SlimeWorldManager 's authors.
Fixing it on WC's end will still cause issues with other plugins if they do the same.
Bugs should be fixed from the root cause of the issue, and not as hot-patches by the plugin developers.

**Comment by DuneSciFye** [comment]
They have been able to fix it!
