### ISSUE TITLE
Autosell doesn't work with ExcellentShop

### ISSUE THREAD

**Issue by Ledovecek** [BG-Software-LLC/WildChests#217]
### Minecraft's Version

1.20.1

### Plugin's Version

2023.3

### Describe the bug

Even if the configuration is set to automatically sell items, nothing is sold.

### To Reproduce

-

### Additional Information

Because of github text formatting: 

**Configuration:** https://hastebin.com/share/ahuhegumak.yaml
**Log:** [latest.log](https://github.com/BG-Software-LLC/WildChests/files/13920918/log.log) (Check line 1430)

Using ExcellentShop v4.8.1

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by OmerBenGera** [comment]
Closing this as it seems to be fixed
If the issue still occurs on latest dev build, let me know
