### ISSUE TITLE
Link chests only remember the last link on restart if you link more than two together

### ISSUE THREAD

**Issue by ArmonicPvP** [BG-Software-LLC/WildChests#222]
### Minecraft's Version

paper-1.20.4-485

### Plugin's Version

2023.3-b35

### Describe the bug

Link chests only remember the last link on restart if you link more than two together. Before a restart, it remembers both,

### To Reproduce

Link a chest to two other link chests, then restart the server.

**Comment by OmerBenGera** [comment]
You can only link one chest to another. A chest cannot be linked to two different chests. It doesn't make a lot of sense neither.
How do you link a chest to two different chests?

**Comment by ArmonicPvP** [comment]
Its practical use involves removing the need for an ice system in an item storage system. This removes a lot of redstone overhead. Linking a chest to multiple other chests is very practical. Ender chests have a similar functionality, except other players and hoppers can't access my enderchest. (Remember the enderchests mod with the 3 rectangles you could dye to change the code?) Giving that functionality of allowing a chest to link to multiple others really does have a lot of good technical use, and from what I've seen the only issue with it right now is that the links don't properly save. The chest items update properly across all chests I have linked to the first one just fine.

**Comment by OmerBenGera** [comment]
You can have multiple chests link to the same chest, however each chest can only link to one chest (technically, similar to the ender chest mod).
I don't understand how you link a chest to two different chests.

**Comment by ArmonicPvP** [comment]
You explained what I was saying better. Sorry for that confusion. I am having an issue where it doesn't save correctly after restarting. The workaround for me has been linking chest c to chest b and chest b to chest a. I will test with the new builds and let you know if the issue persists.

**Comment by OmerBenGera** [comment]
Interesting.
I cannot seem to replicate the issue neither.
Please test out latest dev build, and if the issue persists, explain in detail how to replicate it (how many chests you have, which chest is linked to which, etc)

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Hey, check out latest dev build, I fixed a similar issue in #261

**Comment by OmerBenGera** [comment]
I am closing this for now
If the issue still occurs, let me know
