### ISSUE TITLE
Sell chests selling custom items

### ISSUE THREAD

**Issue by NeoNixStar** [BG-Software-LLC/WildChests#228]
### Minecraft's Version

1.20.4

### Plugin's Version

2024.1

### Describe the bug

The sell chest is selling custom items in my server

### To Reproduce

Make a custom items and put them in the chest or install another pluggin with customitems

### Additional Information

![2024-05-30_15 43 08](https://github.com/BG-Software-LLC/WildChests/assets/75399221/7abc389c-fa61-412f-baa3-69d734b693e6)
The copper ingot value its 40$
The coin value its 1$

**Comment by OmerBenGera** [comment]
What shops plugin do you use?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this for now
If the issue still occurs, let me know
