### ISSUE TITLE
Sell Chests stop working with ExcellentShop V4.10.x

### ISSUE THREAD

**Issue by InvisibleSpiders** [BG-Software-LLC/WildChests#229]
### Minecraft's Version

Paper 1.20.4 Build 496

### Plugin's Version

WildChests v2024.1
ExcellentShop v4.10.1

### Describe the bug

Upgrading ExcellentShop from V4.9.0 to V4.10.0 or V4.10.1 no longer supports selling via chests in WildChests.
No errors occur.

### To Reproduce

Install ExcellentShop v4.9 and WildChests (most recent build).
Configure WildChests to recognize ExcellentShop.
Place a SellChest, and attempt to sell. It should work fine.
Stop the server, and upload V4.10.1 of ExcellentShop and reboot.
Attempt to sell items in the sell chest again, it won't take any items.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by InvisibleSpiders** [comment]
Build 44 works great with v4.10.1 of ExcellentShop, thank you for the quick fix!
