### ISSUE TITLE
Doesn't recognize newest CoreProtect

### ISSUE THREAD

**Issue by InvisibleSpiders** [BG-Software-LLC/WildChests#230]
### Minecraft's Version

Paper 1.20.4 Build 496

### Plugin's Version

WildChests 2024.1
CoreProtect v22.4

### Describe the bug

Console throws a warning that WildChests doesn't recognize the most recent build of CoreProtect.

### To Reproduce

Install both plugins. Boot server and view console.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by InvisibleSpiders** [comment]
It looks to have solved that issue, thanks!
