### ISSUE TITLE
EssentialsX seems to not be read by WildChests sellchest.

### ISSUE THREAD

**Issue by deadspidervenom** [BG-Software-LLC/WildChests#236]
### Minecraft's Version

1.20.6

### Plugin's Version

DEV 50

### Describe the bug

The sell chest is not selling anything

![image](https://github.com/BG-Software-LLC/WildChests/assets/12871122/a77a7e19-7b5e-46b5-a4a9-c38eef426820)

Prices provider is set to "prices-provider: 'Essentials'" and diamonds has a value.

Could this be a conflict with "EssentialsX"?

Plugins i am using for economy
EssentialsX
Vault
Funds (i have a currency setup and hooked into vault)

### To Reproduce

install all valid plugins
Wildchests DEV 50
EssentialsX
Vault
Funds

Edit the wild chests config to use essentials and assure the essentials has diamonds as a valid worth.

Try to sell diamonds via wildchest sell chest.

**Comment by OmerBenGera** [comment]
I cannot replicate the issue, it seems to work fine for me.
I am using `WildChests v2024.1 b50` and `EssentialsX v2.21.0-dev+93-3a6fdd9`

**Comment by deadspidervenom** [comment]
> I cannot replicate the issue, it seems to work fine for me. I am using `WildChests v2024.1 b50` and `EssentialsX v2.21.0-dev+93-3a6fdd9`

After testing i think it has to do with the "/wildchests reload" as at the time i was making config edits than reloading. However on restart it now works.

**Comment by OmerBenGera** [comment]
You must restart so the new prices provider will be used :)

**Comment by deadspidervenom** [comment]
> You must restart so the new prices provider will be used :)

Might be a good idea to include that in the config any other valid spot, probably why other people had similar issues.
