### ISSUE TITLE
Chest Items lose Data/quantity on 1.21

### ISSUE THREAD

**Issue by InvisibleSpiders** [BG-Software-LLC/WildChests#237]
### Minecraft's Version

MC V 1.21, Paper 1.21 Build 39

### Plugin's Version

Build 50 / Latast

### Describe the bug

Updating server from Paper 1.20.4, to Paper 1.21 causes stored items in plugin chests to lose specific data and quantity.
For example, banners lose their patterns, custom enchant books lose their enchants (ie EnchantsSquared). Stacks of items show only a quantity of 1. 

### To Reproduce

Load up server on 1.20.4, place a WildChests chest.
Store several items (stacks, custom banners, etc).
Save and shut-down server.
Update to paper 1.21.
Boot server and check the chest items.

### Additional Information

[Config.yml Pastebin]( https://pastebin.com/28MStb1A)

**Comment by OmerBenGera** [comment]
Check out latest dev build, should be fixed
You must run for once the new jar on the old version (1.20.4), only then upgrade to 1.20.6/1.21.

**Comment by InvisibleSpiders** [comment]
That's awesome, thank you for your hard work!
I will give this a go in a few hours.

**Comment by InvisibleSpiders** [comment]
> Check out latest dev build, should be fixed You must run for once the new jar on the old version (1.20.4), only then upgrade to 1.20.6/1.21.

This new build seems to have solved the issue. Thanks again!
