### ISSUE TITLE
Stacking items over vanilla stack limit

### ISSUE THREAD

**Issue by ItIsJosh** [BG-Software-LLC/WildChests#239]
### Minecraft's Version

Pufferfish+ 1.20.4

### Plugin's Version

WildChests 2024.1-b44
Rosestacker 1.5.20

### Describe the bug

When a chunk collector picks up a rosestacker item stack for an item that's max stack size is less than 64 (eg ender pearls). The items will be placed in the container as a 64 item stack, rather than the items max stack size.

### To Reproduce

1. Drop 64 enderpearls onto the ground
2. Have them merge into 1 stack
3. Place down a chunk collector in that chunk
4. Take out a 64 stack of ender pearls (Should be 4 stacks of 16)

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by ItIsJosh** [comment]
Yep, that fixed it! Thank you :)
