### ISSUE TITLE
RoseStacker dupe bug

### ISSUE THREAD

**Issue by ItIsJosh** [BG-Software-LLC/WildChests#243]
### Minecraft's Version

Pufferfish 1.20.4

### Plugin's Version

2024.2-b53

### Describe the bug

If the size of an item stack is bigger than the available slots in a suction chest the items will be added to the container but not removed from the item stack. 

### To Reproduce

1. Place chunk collector
2. Fill all but 1 slot with an unsellable item
3. Create a RoseStacker* stack that has over 64 items
4. Take item from chest container 
5. Repeat last step
*Might work with other stacking plugins iv not tested.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by OmerBenGera** [comment]
I am closing this for now
If the issue still occurs, let me know
