### ISSUE TITLE
wildchest and wildtools 

### ISSUE THREAD

**Issue by houaricarl** [BG-Software-LLC/WildChests#244]
### Minecraft's Version

latest version of purpur 1.20.2

### Plugin's Version

latest version of wildtools and wildchest

### Describe the bug

it doesnt startup at all when running the server
![image](https://github.com/user-attachments/assets/76d49c2e-7c59-4a75-a1a3-80fe9a34a4bc)

### To Reproduce

N/A

### Additional Information

no changes on config on them both

**Comment by OmerBenGera** [comment]
My plugins do not support 1.20.2.
They only support 1.20.4/1.20.6
