### ISSUE TITLE
Storage unit can’t create new records to the database

### ISSUE THREAD

**Issue by RCLSyCo** [BG-Software-LLC/WildChests#245]
### Minecraft's Version

Running 1.21.1
paper-1.21-120.jar

### Plugin's Version

2024.2 Latest stable build 
WildChests-2024.2.jar

WildChests-2024.1-b50.jar was the last Dev build that didn't have the error
51-54 including the latest stable build all have the error.
![image](https://github.com/user-attachments/assets/639d6996-b247-4364-a719-ba9701c0d2fd)

### Describe the bug

When you place any chest of the storage unit type it throws an error and can’t create a new record in The database. All the other chest types are good. If you manually add the record to the database or if the chest was placed before this issue was introduced then there are no issues since saving and loading from the database is fine. It’s just not able to run the event that create the first record when you place the storage unit chest. 

This same issue is also in the wildloaders plugin when placing a chunk loader 

### To Reproduce

Place a brand new storage chest. It will show the error it couldnt trigger the event on placement. restart server and the chest will be a normal one since nothing was written to the database,

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by RCLSyCo** [comment]
Confirming WildLoaders-2024.2-b33.jar and WildChests-2024.2-b55.jar no longer have the issue. Thank you.
