### ISSUE TITLE
Cant add bowl to crafter chest

### ISSUE THREAD

**Issue by ultravi0let27** [BG-Software-LLC/WildChests#249]
### Minecraft's Version

1.20.6

### Plugin's Version

2024.3

### Describe the bug

when adding bowl in the config it just make the whole plugin stop working

### To Reproduce

add bowl in crafter chest recipe. execute /wildchest reload

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by ultravi0let27** [comment]
I will only be able to do so tomorow

**Comment by ultravi0let27** [comment]
It does not work in the #59 dev

**Comment by ultravi0let27** [comment]
Nvm it worked
