### ISSUE TITLE
Auto-suction bug with range

### ISSUE THREAD

**Issue by Xitryne** [BG-Software-LLC/WildChests#252]
### Minecraft's Version

Paper 1.20.4

### Plugin's Version

2024.3

### Describe the bug

The chest is able to suck up to the stand armor but as you can see on the left, if I put an object at this distance but on the other side then it does not suck up to 2 blocks but 1 block. While on the side of the stand armor it sucks up to 2 blocks and in the config I put a range of 2

### To Reproduce

^^

### Additional Information

![image](https://github.com/user-attachments/assets/b4509b7e-cbe1-40cb-bbb9-2127ad017698)

**Comment by OmerBenGera** [comment]
Show me how you configured your chunk-collector chest please

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed
