### ISSUE TITLE
After the server restarts, entering the chunks with a large number of wildchests will cause a significant delay.

### ISSUE THREAD

**Issue by Noogear** [BG-Software-LLC/WildChests#257]
### Minecraft's Version

This server is running Leaf version 1.21.1-DEV-ver/1.21.1@4cbc1af (2024-10-30T15:50:49Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
* You are running the latest version
Previous: 1.21.1-DEV-c6c6224 (MC: 1.21.1)

### Plugin's Version

WildChests-2024.3-b60

### Describe the bug

https://spark.lucko.me/rRmDxX4wi1
https://spark.lucko.me/kDGFw0MWhi

After the server restarts, entering the chunks with a large number of wildchests will cause a significant delay.

### To Reproduce

Restart the server and teleport to the chunks with a large number of wildchests.

### Additional Information

Do you have any clue? I can replicate it locally. it only causes lag when there are special chests of this plugin in the chunk. If you need it, I can send the world save file.

**Comment by Noogear** [comment]
[config.zip](https://github.com/user-attachments/files/17595034/config.zip)

**Comment by Noogear** [comment]
When placing the STORAGE_UNIT that supports chunk collection, it seems the most obvious. If you need the complete server files, I can send them to you.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by Noogear** [comment]
> Check out latest dev build, let me know if it is fixed

https://spark.lucko.me/VmNbNgm6Bu
I tested it locally and the effect was very significant! Thank you very much! This problem has troubled me for a long time.

**Comment by OmerBenGera** [comment]
> > Check out latest dev build, let me know if it is fixed
> 
> https://spark.lucko.me/VmNbNgm6Bu I tested it locally and the effect was very significant! Thank you very much! This problem has troubled me for a long time.

Glad it's better now.
If you encounter any other issues, make sure you open bug reports.

Closing this for now :)

**Comment by Noogear** [comment]
> > > Check out latest dev build, let me know if it is fixed
> > 
> > 
> > https://spark.lucko.me/VmNbNgm6Bu I tested it locally and the effect was very significant! Thank you very much! This problem has troubled me for a long time.
> 
> Glad it's better now. If you encounter any other issues, make sure you open bug reports.
> 
> Closing this for now :)

[log.txt](https://github.com/user-attachments/files/17611524/log.txt)
Is there a way to load the chests without lagging the main thread? I'm worried that when the number of chests is large enough, it will lag the server for more than one minute... This seems to trigger some restart and heartbeat mechanisms of the server.

**Comment by OmerBenGera** [comment]
Open a new issue regarding this, I will look into this as well
