### ISSUE TITLE
Loading chests will occupy the server's main thread for a very long time.

### ISSUE THREAD

**Issue by Noogear** [BG-Software-LLC/WildChests#258]
### Minecraft's Version

This server is running Leaf version 1.21.1-DEV-ver/1.21.1@6fff957 (2024-11-03T16:10:53Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
* You are running the latest version
Previous: 1.21.1-DEV-64e3cd9 (MC: 1.21.1)

### Plugin's Version

WildChests-2024.3-b61

### Describe the bug

[log.txt](https://github.com/user-attachments/files/17611631/log.txt)
As the number of chests increases, the server will occupy the main thread for a long time when loading these chests.

### To Reproduce

https://github.com/BG-Software-LLC/WildChests/issues/257 The follow-up of this issue

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it it's better

**Comment by Noogear** [comment]
> Check out latest dev build, let me know if it it's better

Thank you very much. No errors were seen in the console. Good job!
