### ISSUE TITLE
Error after restarting

### ISSUE THREAD

**Issue by enels0n** [BG-Software-LLC/WildChests#261]
### Minecraft's Version

Paper 1.21.1

### Plugin's Version

WildChests-2024.4-b65 and WildChests-2024.4-b66

### Describe the bug

After restarting, the plugin did not load, giving an error. Only deleting information about linked chests from the database.db helps.

### To Reproduce

1. Place multiple chests
2. Link
3. Restart
This happened to me twice with the same set of chests. I don't know how to reproduce it exactly.

### Additional Information

[database.db](https://drive.google.com/file/d/1n609swCQ9l0LylV8uTBP0sKy1eNyPFSZ/view?usp=sharing)
[Log](https://pastebin.com/fk7Gg5NV)

**Comment by enels0n** [comment]
And again
![image](https://github.com/user-attachments/assets/e921b184-d47a-463d-9909-7e0b56fe3f07)

**Comment by OmerBenGera** [comment]
For no reason, you have some empty inventories in there (which should never occur)
Latest dev build should handle this correctly and still load, and also print error logs when failing to serialize inventories.

**Comment by enels0n** [comment]
Hello, I tried the new build and I still get errors after restarting, but for a different reason.

Step 1. https://www.youtube.com/watch?v=hRJk-oDMnKQ
Step 2. Restart server

Result:
https://pastebin.com/raw/u73JAtS0
![image](https://github.com/user-attachments/assets/1f97f21b-ee93-421e-8ff4-f9d46cdfbd79)

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by enels0n** [comment]
It worked - the plugin no longer gives an error when restarting. However, sometimes chests unlink from a "chest network".
https://youtu.be/9oeydpzSjYU
![image](https://github.com/user-attachments/assets/e526a3bc-02cd-460c-b56c-e8ad7350113f)

**Comment by OmerBenGera** [comment]
> It worked - the plugin no longer gives an error when restarting. However, sometimes chests unlink from a "chest network". https://youtu.be/9oeydpzSjYU ![image](https://private-user-images.githubusercontent.com/67772926/391234149-e526a3bc-02cd-460c-b56c-e8ad7350113f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5NzQwNjIsIm5iZiI6MTczMjk3Mzc2MiwicGF0aCI6Ii82Nzc3MjkyNi8zOTEyMzQxNDktZTUyNmEzYmMtMDJjZC00NjBjLWI1NmMtZThhZDczNTAxMTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTMwVDEzMzYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0YzFkYjY1M2E0YjAwZjVkNjU3N2U4YzNiNDU2NGU3MTRkNGEyMjhkMmZhYzVlMzBiNzAxYzJiM2M1YTZlZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LyR3HXg0bRrB3lkNiPbtXPFCl3aGZ4HbmlvZLJNdbNU)

Chests that do not have linked xhests will not be linked to anything. In your situation, only 3 chests are linked.

**Comment by enels0n** [comment]
> Chests that do not have linked xhests will not be linked to anything. In your situation, only 3 chests are linked.

The video shows that in the first case, before and after the restart, all the chests are linked to one network. In the second case, the chests are linked to one network before the restart, and after the restart, one of the chests unlinked from the network.
P.s. The screenshot of the table was taken after the second attempt.

**Comment by OmerBenGera** [comment]
The issue happened when you linked the first chest to the 4th one (from right to left).
The first chest should have been unlinked from the original chain and get linked to the 4th chest, however this did not happen and they were still chained together.
The latest dev build should fix this issue.

**Comment by enels0n** [comment]
This?
![image](https://github.com/user-attachments/assets/6fed4738-0811-40c9-83bb-c8ac927024d1)

**Comment by OmerBenGera** [comment]
Check out dev build 70, my bad.

**Comment by enels0n** [comment]
it works! thank you very much!
