### ISSUE TITLE
How to be compatible with the "auto pickup items" when player break the storage unit

### ISSUE THREAD

**Issue by Noogear** [BG-Software-LLC/WildChests#262]
### Minecraft's Version

leaf 1.21.1

### Plugin's Version

2024.4

### Describe the bug

I found a problem. When I use wildchest and wildstacker simultaneously, if wildchest uses wildstacker to stack the items dropped when the storage unit is destroyed, using a plugin like "auto pickup items" will result in only being able to pick up one stack of items, and the remaining items will disappear. Do you have any ideas to make them compatible?

The code is as follows
```
object PickNearItems {

    fun pickNearItems(args: List<Any?>?) {
        pickNearItems(
            args?.get(0) as Player,
            args[1] as Location,
            args[2].coerceInt(),
            args[3].coerceLong()
        )
    }

    fun pickNearItems(player: Player, location: Location, checkRadius: Int, checkDelay: Long) {
        submit(delay = checkDelay) {
            for (item in location.getNearbyEntitiesByType(Item::class.java, checkRadius.toDouble())) {
                if (GuardItemChecker.checkIsGuardItem(item.itemStack)) continue    //This code is used to determine whether the dropped items are on the blacklist.
                if (canFitItem(player, item.itemStack)) item.remove()
            }
        }
    }

    private fun canFitItem(player: Player, item: ItemStack): Boolean {
        val inventory = player.inventory
        var emptySlots = 0
        var availableSpace = 0

        for (stack in inventory.storageContents) {
            if (stack.isNull) {
                emptySlots++
                availableSpace += item.maxStackSize
                continue
            }

            if (stack!!.isSimilar(item)) {
                availableSpace += item.maxStackSize - stack.amount
            }
        }
        val canFit = emptySlots > 0 || availableSpace >= item.amount

        if (canFit) {
            inventory.addItem(item)
        }
        return canFit
    }
}
```

I would be very grateful if the problem could be solved by any means.

### To Reproduce

1. Install wildchest and wildstacker simultaneously.
2. Let wildstacker stack the items dropped when wildchest is destroyed.
3. Install an automatic pickup plugin.
4. Make the number of items in the storage unit exceed 64.
5. Destroy the storage unit.
6. There are only 64 items in the backpack, and the excess items will disappear.

**Comment by OmerBenGera** [comment]
Use WildStacker's API to get the real amount of items

**Comment by Noogear** [comment]
> Use WildStacker's API to get the real amount of items

Could you please provide a code snippet for reference? I would be extremely grateful.

**Comment by OmerBenGera** [comment]
> > Use WildStacker's API to get the real amount of items
> 
> Could you please provide a code snippet for reference? I would be extremely grateful.

You can see how I did it in WildChests:
https://github.com/BG-Software-LLC/WildChests/blob/master/Hooks/WildStacker/src/main/java/com/bgsoftware/wildchests/hooks/StackerProvider_WildStacker.java

**Comment by Noogear** [comment]
Thank you very much!
