### ISSUE TITLE
When Excellentshop sets dynamic prices, selling items using Wildchest doesn't result in a decrease in the selling price.

### ISSUE THREAD

**Issue by Noogear** [BG-Software-LLC/WildChests#263]
### Minecraft's Version

leaf 1.21.1

### Plugin's Version

2024.4

### Describe the bug

When Excellentshop sets dynamic prices, selling items using Wildchest doesn't result in a decrease in the selling price.

### To Reproduce

1. Set a commodity with dynamic prices
2. Put this commodity into the selling chest for sale
3. After the sale is successful, the price does not decrease.

**Comment by OmerBenGera** [comment]
Can you send me a sample of a dynamic prices shop so I can test it out myself?

**Comment by OmerBenGera** [comment]
Check out latest dev build, should be fixed

**Comment by Noogear** [comment]
After testing, it's effective. A perfect job.
