### ISSUE TITLE
Index out of bounds

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/WildChests#46]
**Minecraft's Version**
Yatopia 1.16.5

**Plugin's Version**: -
WildChests-SSBDatabase

**Describe the bug**
When loading up the server with the SQL database this warning was provided here:
[09:18:45 INFO]: [WildChests] Couldn't load the location SuperiorWorld, -2998, 100, 8998
[09:18:45 INFO]: [WildChests] Index 0 out of bounds for length 0

When tping to this area it is a Linked Chest, Wanted to make you aware in case it becomes a further issue.

**Comment by OmerBenGera** [comment]
Wildchests don't have such message, weird.
Probably due to the custom version you use or something, but I think all's good 0.0
