### ISSUE TITLE
TitleEntity threw exception

### ISSUE THREAD

**Issue by Dqgs** [BG-Software-LLC/WildChests#48]
**Minecraft's Version**
The minecraft version your server run on. Use /version to find which version you use.
It's recommended to also mention which jar you use (Spigot, Paper, etc)
MC: 1.12.2 PAPER git-paper-1618
**Plugin's Version**: -
The version of the plugin. If you use a dev build, mention which dev build you use.
WildChests-b15
**Describe the bug**
Place down a sell chests and then put items in there to sell 
**To Reproduce**
Steps to reproduce the bug.

**Additional information**
Additional information that can help understanding the issue.
Config file, clips, etc are more than welcome.
https://pastebin.com/aHvcszWS

**Comment by OmerBenGera** [comment]
update ShopGUIPlus to the latest version.

**Comment by Dqgs** [comment]
It workes perfectly now! Thank you, could you possibly put a warning for other people
