### ISSUE TITLE
plugin does not respect when another plugin cancels the BlockBreakEvent

### ISSUE THREAD

**Issue by snowgears** [BG-Software-LLC/WildChests#49]
My plugin Shop cancels the BlockBreakEvent of a chest if its a Shop within my plugin.

If someone creates a shop on one of your special chests, when that chest is broken, WildChests does not respect the fact that my Shop plugin has already cancelled the event.

**Comment by Skizzles** [comment]
Can confirm
https://youtu.be/QswS2pbm78s

**Comment by OmerBenGera** [comment]
WildChests checks for ignoring of the event in HIGHEST priority. If your Shop plugin for no reason cancels it on HIGHEST or MONITOR priority, then WildChests will not know about it. You should contact your Shop plugin's author and ask them how do they cancel the event, and make sure they use the NORMAL priority instead.
