### ISSUE TITLE
Storage Units are making items disappear

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/WildChests#52]
**Minecraft's Version**
Purpur 1.17.1 build 1260

**Plugin's Version**: -
Dev b18

**Describe the bug**
Items are disappearing and withdrawing from storage units is not working.

**To Reproduce**
See video below

**Additional information**
https://youtu.be/z00nT56coFE

**Comment by OmerBenGera** [comment]
I can't seem to replicate the issue.
Are you able to replicate it on a server with only WildChests installed with Purpur 1.17.1?

**Comment by Skizzles** [comment]
@OmerBenGera 

After further testing and replication this happens when 2 users are updating the chest at the same time. This also is extremely present when you have something like hoppers or slimefun constantly updating the chest.

Seems multiple updates done from different sources is the cause of the issue.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build

**Comment by Skizzles** [comment]
The storage_unit is constantly updating the item in hand  for some reason which makes it hard to move the item
https://screenshots.skizzles.me/wAnA3/lUfosUqa13.mp4

Also confirmed happens with only WildChests

**Comment by OmerBenGera** [comment]
Does it also happen for you on 1.16.5?

**Comment by Skizzles** [comment]
This does happen on 1.16.5 server version as well.

**Comment by OmerBenGera** [comment]
Mind checking it as well on 1.12 and 1.8?
I want to understand since which version it happened, so I know where to start patching it.

**Comment by Skizzles** [comment]
Happens back to 1.8 from my testing

https://screenshots.skizzles.me/wAnA3/soNupoQa97.mp4

**Comment by OmerBenGera** [comment]
So the issue seems with the way the title is updating causing the client to get confused.
I don't know if that's possible to be fixed tbh, hopefully it is somehow.

**Comment by SecretarySami** [comment]
> So the issue seems with the way the title is updating causing the client to get confused.
> I don't know if that's possible to be fixed tbh, hopefully it is somehow.

Hey Omer, was wondering if you had any luck with this by chance ?

**Comment by broken1arrow** [comment]
> 
> 
> So the issue seems with the way the title is updating causing the client to get confused.
> I don't know if that's possible to be fixed tbh, hopefully it is somehow.

Do you update the title async or sync or other inventory update?

**Comment by OmerBenGera** [comment]
> 
> 
> > So the issue seems with the way the title is updating causing the client to get confused.
> > I don't know if that's possible to be fixed tbh, hopefully it is somehow.
> 
> Do you update the title async or sync or other inventory update?

Titles are updated async if I am not wrong.

**Comment by broken1arrow** [comment]
> > > So the issue seems with the way the title is updating causing the client to get confused.
> > > I don't know if that's possible to be fixed tbh, hopefully it is somehow.
> > 
> > 
> > Do you update the title async or sync or other inventory update?
> 
> Titles are updated async if I am not wrong.

Yeah is not that problem then, TS has to give more info like if he use via version. 

I know is client/server issue with update inventory in 17.x so if he use 17 client when testing can explain the issue or use some mods on the client.
