### ISSUE TITLE
WildChests lag or server crasher

### ISSUE THREAD

**Issue by brasilcraft54** [BG-Software-LLC/WildChests#53]
### Minecraft's Version

purpur-1.17.1-1297.jar

### Plugin's Version

WildChests-b20.jar

### Describe the bug

if a player breaks a chest with more than 100k items, the server is super lagged or even crashes, if a player breaks the chest, he deletes the items instead of dropping them on the ground?

### To Reproduce

breaking a wildchests

**Comment by brasilcraft54** [comment]
would be able to remove the items if you break the chest?

**Comment by OmerBenGera** [comment]
Install WildStacker and WildChests will be hooked to it, so it will not drop a lot of items at once.

**Comment by brasilcraft54** [comment]
so the wildstacker is pulling a lot of cpu even using only for items, when I removed it I had a very large tps increase, on 1.17.1 it has problems with cpu usage on other servers and it is not like that on 1.17 .1
