### ISSUE TITLE
Chunk Listeners causing high resource usage

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/WildChests#54]
### Minecraft's Version

1.17.1 Purpur 1308

### Plugin's Version

dev b20

### Describe the bug

You can see that chunk listeners are causing high resource usage.

### To Reproduce

Not sure in this regard. Assume its due to chunk listening on 1.17.

### Additional Information

https://screenshots.skizzles.me/wAnA3/CuYiliLa31.png

**Comment by OmerBenGera** [comment]
Please include the spark as well.

**Comment by Skizzles** [comment]
@OmerBenGera https://spark.lucko.me/8reOCUHw5v

**Comment by OmerBenGera** [comment]
Fixed, sorry for the long waiting time.
