### ISSUE TITLE
Compatibility RoseStacker

### ISSUE THREAD

**Issue by TheRealRude** [BG-Software-LLC/WildChests#55]
### Minecraft's Version

1.16.5

### Plugin's Version

Newest b20

### Describe the bug

When theres for example 1 million stone on the ground in 1 stack, the chunk collector takes all the million stone and put 64 In the chest

### To Reproduce

Install RoseStacker and wildchests and try to collect a stack number higher then 64

**Comment by OmerBenGera** [comment]
RoseStacker's developers are more than welcome to add support for WildChests by registering a new StackerProvider using the API of the plugin.
I am not adding new features to any of my plugins, therefore I am not gonna add support to RoseStacker.
Sorry.

**Comment by TheRealRude** [comment]
Why does your support recommend me to make a post when ur not going to do a single thing... lmfao

**Comment by OmerBenGera** [comment]
> Why does your support recommend me to make a post when ur not going to do a single thing... lmfao

Because I dont see messages on Discord... you are more than welcome to use another plugin if you dont like the situation :)
