### ISSUE TITLE
Casting issue (CONSOLE)

### ISSUE THREAD

**Issue by rentexfamily** [BG-Software-LLC/WildChests#57]
### Minecraft's Version

>.... [15:30:55 INFO]: This server is running Tuinity version git-Tuinity-"9f3435b" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Plugin's Version

Latest dev build

### Describe the bug

I didn't saw the problem but I see every 10-30mins error in console.

Here's error:
https://paste.gg/p/anonymous/9341c68acd974c69a2b0e92e327de508

### To Reproduce

I dont' really know.

**Comment by OmerBenGera** [comment]
That's because you have a plugin from Norska that interacts with WildChests, however he doesn't make sure the clicked chest is a storage unit, causing this exception.
Contact him / send him a link to this issue.
