### ISSUE TITLE
Auto Crafter Chest Not Working

### ISSUE THREAD

**Issue by Reese14** [BG-Software-LLC/WildChests#59]
### Minecraft's Version

Server Version: Paper version git-Paper-781 (MC: 1.16.5)

### Plugin's Version

Latest Dev Version (b20)

### Describe the bug

When putting items into an Auto Crafter Chest (such as iron ingots, redstone dust, etc.), they are not being crafted into their corresponding blocks.

### To Reproduce

Place the chest, put items in it.

**Comment by OmerBenGera** [comment]
Did you configure your chest to craft these items?

**Comment by Reese14** [comment]
I tried looking through the config on where to do that, and couldn't figure out if there was a way to or not. 
Where can I do that, to make sure it works?

**Comment by OmerBenGera** [comment]
> 
> 
> I tried looking through the config on where to do that, and couldn't figure out if there was a way to or not.
> Where can I do that, to make sure it works?

Under your chest, you need to configure a list of items that it will craft

**Comment by Reese14** [comment]
Here is the config file: https://pastebin.com/paqpGev3.
Is it under the 'crafter_chest:' part? If so, gold ingots are listed, and they do not get crafted.

**Comment by OmerBenGera** [comment]
> 
> 
> Here is the config file: https://pastebin.com/paqpGev3.
> Is it under the 'crafter_chest:' part? If so, gold ingots are listed, and they do not get crafted.

Do you put gold nuggets in the chest?

**Comment by Reese14** [comment]
No, I put gold ingots into the chest and nothing happened.

**Comment by OmerBenGera** [comment]
> 
> 
> No, I put gold ingots into the chest and nothing happened.

You must put gold nuggets or gold blocks, as that's the recipes for getting gold ingots.
The items that you put in that list are the results of the crafting recipes, not the ingredients,

**Comment by Reese14** [comment]
Ohhh, I understand. That can be sort of confusing lol.
Thank you!
