### ISSUE TITLE
Storage Units still accepting Slimefun cargo input

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/WildChests#62]
### Minecraft's Version

1.17.1 Purpur dev 1375

### Plugin's Version

dev b21

### Describe the bug

Slimefun cargo still sends to the barrel even when full. Slimefun has code for compatibility for this which I will include in the additional information.

### To Reproduce

https://www.youtube.com/watch?v=4LurB7u6BaM

### Additional Information

https://github.com/Slimefun/Slimefun4/blob/d6be483a329a3bddb2cbbedb5b7a3ddded052555/src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/CargoUtils.java#L326

This was provided when I asked in the SF discord.

**Comment by OmerBenGera** [comment]
If it worked before, look for the latest version that it worked in, and find what they changed that broke it.

**Comment by Skizzles** [comment]
> If it worked before, look for the latest version that it worked in, and find what they changed that broke it.

The items still send correctly to the Storage Unit so nothing is "Broken". The Storage Unit just needs compatibility with cargo for checking when the Storage Unit is full.

**Comment by OmerBenGera** [comment]
> 
> 
> > If it worked before, look for the latest version that it worked in, and find what they changed that broke it.
> 
> The items still send correctly to the Storage Unit so nothing is "Broken". The Storage Unit just needs compatibility with cargo for checking when the Storage Unit is full.

I don't think it's possible unless they add hard-coded support for Storage Units.
