### ISSUE TITLE
not activeating when placed

### ISSUE THREAD

**Issue by beartravels** [BG-Software-LLC/WildChests#64]
### Minecraft's Version

1.17.1 im not the server admin hes too busy today

### Plugin's Version

ive no fuckig idea this is why i use discord

### Describe the bug

when placeing wild chest or storge chest im not getting the particale effects and they dont work

### To Reproduce

idk your the devs

**Comment by OmerBenGera** [comment]
No plugin version, no instructions on how to replicate the issue... Fill the missing information (at least plugin version)

**Comment by broken1arrow** [comment]
I can say effects work on 1.17.1 (but has only use default one).

**Comment by OmerBenGera** [comment]
> I can say effects work on 1.17.1 (but has only use default one).

Open a new issue please.
