### ISSUE TITLE
Inconsistent Selling

### ISSUE THREAD

**Issue by Vyzon** [BG-Software-LLC/WildChests#7]
I have switched to a custom shop plugin and hooked it into WildChests, but now the selling is inconsistent and does this: 
![download](https://user-images.githubusercontent.com/10103575/105937689-0f7ef600-6024-11eb-90b4-4537ddc3a577.png)

**Comment by OmerBenGera** [comment]
You might not have received everything as there are limits to how much you earn due to issues with the economy plugin

**Comment by Vyzon** [comment]
> You might not have received everything as there are limits to how much you earn due to issues with the economy plugin

Not sure tbh, my shop uses vault/essentials for the economy.

**Comment by OmerBenGera** [comment]
Essentials is known to have issues like that where it cannot keep up with more than 1 transaction per second.
If you sell more items, you should receive the money.

**Comment by OmerBenGera** [comment]
Are you able to replicate the issue with another economy plugin / shop plugin?
