### ISSUE TITLE
Bamboo not selling correctly inside of sell chests

### ISSUE THREAD

**Issue by BrisskIcedTea** [BG-Software-LLC/WildChests#70]
### Minecraft's Version

Paper - 1.17.1

### Plugin's Version

2.2.0-DEVb17

### Describe the bug

Bamboo is not being sold correctly inside of sell chests. I have tried defining bamboo several different ways in the config but yet it still does not sell. Every other item that I need to sell, sells correctly, and for the right price. It is just bamboo that is broken. Bamboo is a big resource on my server so I would really appreciate this being fixed. Thanks.

### To Reproduce

The steps to reproduce would be:

1. Setup a sell chest on your server
2. Define in the config to sell bamboo for $x
3. try place bamboo in the chest for sale
4. realize it doesnt work

### Additional Information

This is a pretty self explanatory issue but here is a screenshot of my config with bamboo being defined. #
![Screenshot_408](https://user-images.githubusercontent.com/76797505/138575899-7348cc98-6d44-47df-a63f-55778f280cd8.png)

**Comment by OmerBenGera** [comment]
It works fine for me.

**Comment by OmerBenGera** [comment]
Upload your entire config to pastebin and send it here please.
