### ISSUE TITLE
Chunk Collector + Sell Chest combo not working as expected

### ISSUE THREAD

**Issue by PatrikX23** [BG-Software-LLC/WildChests#77]
### Minecraft's Version

git-Paper-790 (MC: 1.16.5)

### Plugin's Version

2.2.1.28 Dev build #28

### Describe the bug

I created in the config a chest that is a chunk collector and a sell chest combo I got this problem that if you I Drop 1024 diamonds in the chunk its placed only around the half is sold

### To Reproduce

It's happens with RoseStacker and WildStacker too.
1. Make chest with chunk collector mode and sell mode
2. Place this chest
3. Set SGP as price provider and set a random price for diamond to calculate how much the chest sold
4. Give yourself 1024 diamonds and drop it in the chunk
5. And your 1024 diamonds half is going to be sold

### Additional Information
I'm using the latest ShopGuiPlus version 1.67.3
![image](https://user-images.githubusercontent.com/55624438/144707253-a19d1c4b-a9e2-4ef7-9f62-f32ab22554e0.png)

**Comment by OmerBenGera** [comment]
Seems to work fine for me

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by PatrikX23** [comment]
I played with the rosestacker item stacking settings and now it works as I expected.
