### ISSUE TITLE
WildChests no AutoCrafter or Sell_Chest

### ISSUE THREAD

**Issue by verxii** [BG-Software-LLC/WildChests#78]
### Minecraft's Version

Client Version: 1.12.2, Server version; SPIGOT 1.12.2

### Plugin's Version

WildChests 2.2.1

### Describe the bug

The plugin itself successfully loads, green in /pl and the commands do work. But upon spawning a Sell_Chest or Crafter_Chest, neither of them function even off the default config.

### To Reproduce

To reproduce this bug, simply use it on a 1.12.2 SPIGOT server. Confirmed it on a LAN and dedicated host server. Issue was the same regardless.

### Additional Information

Can attach a video if need be, however it should be pretty well self explanatory.

**Comment by verxii** [comment]
A side note, no console errors whatsoever.

**Comment by OmerBenGera** [comment]
When you place the chests, do they have custom names in their titles?

**Comment by verxii** [comment]
Nothing besides the defaults. I am not home at.the moment, but the Sell Chest inventory title was 'Drop items in here to sell them' or something along those lines. Default config with the price handler being set to Essentials or WildChests

**Comment by verxii** [comment]
They have prices, regardless of the price handler. Crafter chest doesn't craft gold ingots even on default config.

**Comment by OmerBenGera** [comment]
I'll look into that.

**Comment by verxii** [comment]
![2021-12-09_18 26 50](https://user-images.githubusercontent.com/93841927/145496730-a64c0266-88b0-421e-9baa-8cc7a2270336.png)

https://paste-bin.xyz/22202 <-- WildChests Config

https://paste-bin.xyz/22203 <-- Essentials worth.yml

Why is the sell_chest not working? Also, the chunk-collector is also non functional. All still on 1.12.2

**Comment by OmerBenGera** [comment]
As I said before, I will look into that.

**Comment by OmerBenGera** [comment]
It works fine for me.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by verxii** [comment]
Nope, same issue as before, on a default config, fresh JAR it just does not seem to work

**Comment by OmerBenGera** [comment]
> Nope, same issue as before, on a default config, fresh JAR it just does not seem to work

As I said, it works fine for me on a fresh setup.
You do something wrong or there might be an issue with your prices provider that the items just don't get sold, and it has nothing to do with the chunk-collector.

**Comment by verxii** [comment]
Chunk collector also doesnt work

**Comment by verxii** [comment]
Only the linked chests seem to work, on a fresh setup.

**Comment by OmerBenGera** [comment]
> Only the linked chests seem to work, on a fresh setup.

Try selling the items using a regular sell chest, check if it works.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response.
If it still happens, reply here.
