### ISSUE TITLE
EconomyShopGUI-Premium

### ISSUE THREAD

**Issue by GameWatchProjects** [BG-Software-LLC/WildChests#85]
### Minecraft's Version

Minecraft 1.17.1 (Paper)

### Plugin's Version

Wildchests 2.2.3
EconomyShopGUI-Premium v2.2.1 (not the free Version)

### Describe the bug

Ingame no Problems, but by startup or reload the server, in the command line this message is shown:

[WildChests]: Loaded class me.gypopo.economyshopgui.api.EconomyShopGUIHook from EconomyShopGUI-Premium v2.2.1 which is not a depend, softdepend or loadbefore of this plugin.

### To Reproduce

Add in the config.yml the option to use the prices from EconomyShopGUI

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
