### ISSUE TITLE
Destroyed a storage unit with over 10k ingots, didnt get them back

### ISSUE THREAD

**Issue by FourNineRugz** [BG-Software-LLC/WildChests#94]
### Minecraft's Version

Purpur 1.18.1

### Plugin's Version

Latest plugin version

### Describe the bug

When destroying a storage unit with a mass amount of units, items get lost. Also, coreprotect does not detect these changes

### To Reproduce

When destroying a storage unit with a mass amount of units, items get lost. Also, coreprotect does not detect these changes

**Comment by OmerBenGera** [comment]
Maybe you have a plugin that removes the items to prevent lag?

**Comment by OmerBenGera** [comment]
Try replicating it on a server with only WildLoaders installed.

**Comment by McBesser** [comment]
I'll join you here and don't create a new report. I have the same problem. It would be desirable if you can only dismantle an empty storage unit in this case or with not too many items. Possibly the option could be added somehow, that would be nice.

**Comment by OmerBenGera** [comment]
> I'll join you here and don't create a new report. I have the same problem. It would be desirable if you can only dismantle an empty storage unit in this case or with not too many items. Possibly the option could be added somehow, that would be nice.

Does it happen when only WildLoaders installed?
I know about plugins that prevent too many items to spawn, that is why I am asking

**Comment by McBesser** [comment]
I tested it on a server that didn't have that many plugins on it. 12.5k is still possible but at 25k everything is gone, I think it will also be more paper which deletes the items. But it doesn't really matter. It would be better not to be able to break them down until there are too many items in the box. 
![grafik](https://user-images.githubusercontent.com/53328146/149383795-22ef9709-984d-4b17-abdb-cfee231c19e3.png)

**Comment by OmerBenGera** [comment]
You have FastAsyncWorldEdit, which has a items limiter...
Again, test it on a server with **only** WildChests installed to make sure it's an issue with the plugin, and not other plugins deleting the items.

**Comment by OmerBenGera** [comment]
> I tested it on a server that didn't have that many plugins on it. 12.5k is still possible but at 25k everything is gone, I think it will also be more paper which deletes the items. But it doesn't really matter. It would be better not to be able to break them down until there are too many items in the box. ![grafik](https://user-images.githubusercontent.com/53328146/149383795-22ef9709-984d-4b17-abdb-cfee231c19e3.png)

You have FastAsyncWorldEdit, which has a items limiter...
Again, test it on a server with **only** WildChests installed to make sure it's an issue with the plugin, and not other plugins deleting the items.

**Comment by McBesser** [comment]
now 25k dropped
![grafik](https://user-images.githubusercontent.com/53328146/149401311-43f0bda9-f448-444f-8214-ca6fb0ecff9a.png)

it is not good, pls add a optional break protection (now 25k there are also boxes with 3kk items... I can't imagine that it's supposed to be that good when it's lying around )

**Comment by FourNineRugz** [comment]
Even without FAWE installed, I agree with McBesser because in the rare chance someone may have 25,50, maybe even 100k items in a storage unit (not sure if that's possible) and they break it... sounds like a disaster waiting to happen.

**Comment by FourNineRugz** [comment]
And the fact that CoreProtect doesnt detect changes in a storage unit may cause problems as well. But that's just icing on the cake if that's to be addressed

**Comment by OmerBenGera** [comment]
> Even without FAWE installed, I agree with McBesser because in the rare chance someone may have 25,50, maybe even 100k items in a storage unit (not sure if that's possible) and they break it... sounds like a disaster waiting to happen.

You can disable the items limiter of FAWE in their config.
If you are worried about too many items to be dropped on ground, then you can use an items-stacker plugin or add a limit for storage units. This is not something that WildChests should restrict - I will never restrict breaking of blocks only because they have too many items. Creating a "bedrock" block that cannot be broken will never be a thing.
About CoreProtect not working with WildChests, that's because WildChests doesn't have support for CoreProtect.

Closing this one, there's no bug on behalf of the plugin.

**Comment by McBesser** [comment]
I personally like the behavior of Fawe that it deletes items over 10k. I also think the behavior is good as the items are basically lying around. I also like that a storage unit stores unlimited items. The only thing that would be desirable would be an option where you can deposit from how many items it is possible to dismantle the storage unit. But it looks as if this will not be implemented, which is a real shame somehow. At the moment this leads to frustration of the players and they don't really want to put an additional plugin on it, which in turn causes different behavior that you don't want to have. 

but don't misunderstand the plugin is very nice and I'm glad to be able to use it.

**Comment by OmerBenGera** [comment]
> I personally like the behavior of Fawe that it deletes items over 10k. I also think the behavior is good as the items are basically lying around. I also like that a storage unit stores unlimited items. The only thing that would be desirable would be an option where you can deposit from how many items it is possible to dismantle the storage unit. But it looks as if this will not be implemented, which is a real shame somehow. At the moment this leads to frustration of the players and they don't really want to put an additional plugin on it, which in turn causes different behavior that you don't want to have.
> 
> but don't misunderstand the plugin is very nice and I'm glad to be able to use it.

You can just take off items out of the storage units if you wish instead of breaking it...
You on one hand don't want to disable items limiter, on the other hand you want to limit items from stroage units.
On one hand, you want storage units to be unlimited, on the other hand you want them to not be breakable if they exceed a specific amount of items inside them...
It makes no sense.

**Comment by McBesser** [comment]
what exactly doesn't make sense?

from a player's point of view:
they break the box, all items are gone + the box. The box cannot be crafted and is valuable for the players. So it leads to double frustration.

from our point of view:
The item despawn behavior is desired, but not the "special stacking" with another plugin.

it was just a suggestion... let's call it a feature request. If that's too complicated to provide the option in a config or you don't want it, then that's fine. We all like the plugin the way it is, only leads to frustration in the case of individual players who intentionally or unintentionally fully dismantle the crate.

thanks again for the great plugin, it's really nice.

**Comment by OmerBenGera** [comment]
> 

I understand what you want, however again - this can be established by using an items-stacker, or disabling your items limiter. If you don't want items to get deleted, don't use an items-limiter; simple as that.
I am glad you like the plugin, hopefully you'll find a setup that works for you and your players. If you really need somehow the feature you wanted, you can fork the plugin and implement it on your own :)
