### ISSUE TITLE
4 Separate Errors!

### ISSUE THREAD

**Issue by TeQTabanca** [BG-Software-LLC/WildChests#97]
### First Mistake
**I get an error if i add items to storage chest.**

- [08:43:18 WARN]: [WildChests] Task #46974 for WildChests v2.2.3 generated an exception
- java.lang.ClassCastException: class net.minecraft.server.v1_12_R1.TileEntityChest cannot be cast to class com.bgsoftware.wildchests.nms.NMSInventory_v1_12_R1$TileEntityWildChest (net.minecraft.server.v1_12_R1.TileEntityChest is in unnamed module of loader 'app'; com.bgsoftware.wildchests.nms.NMSInventory_v1_12_R1$TileEntityWildChest is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @2cd2abd9)
- at com.bgsoftware.wildchests.nms.NMSInventory_v1_12_R1.getTileEntity(NMSInventory_v1_12_R1.java:158) ~[WildChests-2.2.3.jar:?]
- at com.bgsoftware.wildchests.nms.NMSInventory_v1_12_R1.openPage(NMSInventory_v1_12_R1.java:125) ~[WildChests-2.2.3.jar:?]
- at com.bgsoftware.wildchests.objects.chests.WChest.openPage(WChest.java:204) ~[WildChests-2.2.3.jar:?]
- at com.bgsoftware.wildchests.objects.chests.WStorageChest.lambda$updateInventory$3(WStorageChest.java:402) ~[WildChests-2.2.3.jar:?]
- at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
- at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
- at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
- at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
- at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
- at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
- at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
- at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
- at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
- at com.bgsoftware.wildchests.objects.chests.WStorageChest.updateInventory(WStorageChest.java:402) ~[WildChests-2.2.3.jar:?]
- at com.bgsoftware.wildchests.objects.chests.WStorageChest.lambda$update$0(WStorageChest.java:218) ~[WildChests-2.2.3.jar:?]
- at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[server.jar:git-Spigot-79a30d7-acbc348]
- at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [server.jar:git-Spigot-79a30d7-acbc348]
- at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [server.jar:git-Spigot-79a30d7-acbc348]
- at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-79a30d7-acbc348]
- at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-79a30d7-acbc348]
- at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-79a30d7-acbc348]
- at java.lang.Thread.run(Thread.java:829) [?:?]

### Second Mistake
**I get an error if I don't confirm opening the second page in the wide chest.**

![when you do not confirm the second page](https://user-images.githubusercontent.com/89253304/149088301-b4b960ac-ea38-494c-8421-88ee599d841c.png)

- [08:59:07 WARN]: [WildChests] Task #85805 for WildChests v2.2.3 generated an exception
- java.lang.ClassCastException: class net.minecraft.server.v1_12_R1.TileEntityChest cannot be cast to class com.bgsoftware.wildchests.nms.NMSInventory_v1_12_R1$TileEntityWildChest (net.minecraft.server.v1_12_R1.TileEntityChest is in unnamed module of loader 'app'; com.bgsoftware.wildchests.nms.NMSInventory_v1_12_R1$TileEntityWildChest is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @2cd2abd9)
- at com.bgsoftware.wildchests.nms.NMSInventory_v1_12_R1.getTileEntity(NMSInventory_v1_12_R1.java:158) ~[WildChests-2.2.3.jar:?]
- at com.bgsoftware.wildchests.nms.NMSInventory_v1_12_R1.openPage(NMSInventory_v1_12_R1.java:125) ~[WildChests-2.2.3.jar:?]
- at com.bgsoftware.wildchests.objects.chests.WChest.openPage(WChest.java:204) ~[WildChests-2.2.3.jar:?]
- at com.bgsoftware.wildchests.listeners.InventoryListener.lambda$handleUpgrade$3(InventoryListener.java:171) ~[WildChests-2.2.3.jar:?]
- at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[server.jar:git-Spigot-79a30d7-acbc348]
- at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [server.jar:git-Spigot-79a30d7-acbc348]
- at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [server.jar:git-Spigot-79a30d7-acbc348]
- at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-79a30d7-acbc348]
- at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-79a30d7-acbc348]
- at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-79a30d7-acbc348]
- at java.lang.Thread.run(Thread.java:829) [?:?]

**If i confirm i get error.**

![if i confirm i get error](https://user-images.githubusercontent.com/89253304/149089615-95018a77-e335-493c-ab26-b49afb387aed.png)

- [09:12:28 WARN]: [WildChests] Task #115504 for WildChests v2.2.3 generated an exception
- java.lang.ClassCastException: class net.minecraft.server.v1_12_R1.TileEntityChest cannot be cast to class com.bgsoftware.wildchests.nms.NMSInventory_v1_12_R1$TileEntityWildChest (net.minecraft.server.v1_12_R1.TileEntityChest is in unnamed module of loader 'app'; com.bgsoftware.wildchests.nms.NMSInventory_v1_12_R1$TileEntityWildChest is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @2cd2abd9)
- at com.bgsoftware.wildchests.nms.NMSInventory_v1_12_R1.getTileEntity(NMSInventory_v1_12_R1.java:158) ~[WildChests-2.2.3.jar:?]
- at com.bgsoftware.wildchests.nms.NMSInventory_v1_12_R1.openPage(NMSInventory_v1_12_R1.java:125) ~[WildChests-2.2.3.jar:?]
- at com.bgsoftware.wildchests.objects.chests.WChest.openPage(WChest.java:204) ~[WildChests-2.2.3.jar:?]
- at com.bgsoftware.wildchests.listeners.InventoryListener.lambda$handleUpgrade$3(InventoryListener.java:171) ~[WildChests-2.2.3.jar:?]
- at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[server.jar:git-Spigot-79a30d7-acbc348]
- at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [server.jar:git-Spigot-79a30d7-acbc348]
- at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [server.jar:git-Spigot-79a30d7-acbc348]
- at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-79a30d7-acbc348]
- at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-79a30d7-acbc348]
- at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-79a30d7-acbc348]
- at java.lang.Thread.run(Thread.java:829) [?:?]

**If I try to open pages after confirming, I get an error.**

- [09:19:31 ERROR]: Could not pass event InventoryClickEvent to WildChests v2.2.3
- org.bukkit.event.EventException: null
- at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-79a30d7-acbc348]
- at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-79a30d7-acbc348]
- at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [server.jar:git-Spigot-79a30d7-acbc348]
- at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [server.jar:git-Spigot-79a30d7-acbc348]
- at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1893) [server.jar:git-Spigot-79a30d7-acbc348]
- at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [server.jar:git-Spigot-79a30d7-acbc348]
- at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [server.jar:git-Spigot-79a30d7-acbc348]
- at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-79a30d7-acbc348]
- at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
- at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
- at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-79a30d7-acbc348]
- at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [server.jar:git-Spigot-79a30d7-acbc348]
- at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-79a30d7-acbc348]
- at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-79a30d7-acbc348]
- at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-79a30d7-acbc348]
- at java.lang.Thread.run(Thread.java:829) [?:?]
- Caused by: java.lang.ClassCastException: class net.minecraft.server.v1_12_R1.TileEntityChest cannot be cast to class com.bgsoftware.wildchests.nms.NMSInventory_v1_12_R1$TileEntityWildChest (net.minecraft.server.v1_12_R1.TileEntityChest is in unnamed module of loader 'app'; com.bgsoftware.wildchests.nms.NMSInventory_v1_12_R1$TileEntityWildChest is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @2cd2abd9)
- at com.bgsoftware.wildchests.nms.NMSInventory_v1_12_R1.getTileEntity(NMSInventory_v1_12_R1.java:158) ~[WildChests-2.2.3.jar:?]
- at com.bgsoftware.wildchests.nms.NMSInventory_v1_12_R1.openPage(NMSInventory_v1_12_R1.java:125) ~[WildChests-2.2.3.jar:?]
- at com.bgsoftware.wildchests.objects.chests.WChest.openPage(WChest.java:204) ~[WildChests-2.2.3.jar:?]
- at com.bgsoftware.wildchests.objects.chests.WChest.onInteract(WChest.java:285) ~[WildChests-2.2.3.jar:?]
- at com.bgsoftware.wildchests.listeners.InventoryListener.onChestInteract(InventoryListener.java:120) ~[WildChests-2.2.3.jar:?]
- at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
- at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
- at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
- at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
- at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-Spigot-79a30d7-acbc348]
- ... 15 more

### Third Mistake
**Chest selling items not working.**

![items i want to sell](https://user-images.githubusercontent.com/89253304/149092642-8015d8d5-4ff7-4ac3-8e82-0bbdf4939d1b.png)

![items i want to sell 2](https://user-images.githubusercontent.com/89253304/149094493-87a38dc6-42e2-4b8a-b5d2-5f0491a36e55.png)

**But nothing happens.**

**Auto crafter chest is not working either.**

### And The Last Mistake

**Particles not working.**

![particle settings](https://user-images.githubusercontent.com/89253304/149097647-704ea047-3775-41b7-9a74-25b65951dcd9.png)

![particles not working in game](https://user-images.githubusercontent.com/89253304/149097674-3520e9e1-dab1-4fa7-936d-a3f4c457cfb1.png)

**Comment by TeQTabanca** [comment]
### If i restart the server the chests look like this

![chests look like this](https://user-images.githubusercontent.com/89253304/149115933-e041c819-df7e-410e-a833-5184542908c9.png)


### If i right click on the chest it starts showing up

![chest opened](https://user-images.githubusercontent.com/89253304/149117674-9fbc1a84-35f2-483d-bbe9-d1307c8a3630.png)

![chest closed](https://user-images.githubusercontent.com/89253304/149117512-abe90db0-84f0-4b9a-aeea-32934fa38983.png)

**Comment by OmerBenGera** [comment]
This is not how you report a bug.
Make separate issues for each of the bugs. Error logs should be pasted via pastebin, and follow the format.
